   1     1         Hopf Function:   2.25000E-01

   1     1         Eigenvalues  :   Stable:   0
   1     1         Eigenvalue  1:   2.25000E-01  -1.98730E+00
   1     1         Eigenvalue  2:   2.25000E-01   1.98730E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     1  EP    1   2.00000E+00   3.38018E+00   2.00000E+00   2.72500E+00
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     2   0        2.01018E+00   3.37506E+00
   1     2   1        2.01021E+00   3.37510E+00
   1     2   2        2.01021E+00   3.37510E+00

===============================================

  BR    PT  IT         PAR           L2-NORM
   1     2   0        2.02042E+00   3.37011E+00
   1     2   1        2.02047E+00   3.37020E+00
   1     2   2        2.02047E+00   3.37020E+00

   1     2         Fold Function:   5.14187E-01
   1     2         BP   Function:   1.58788E+01
   1     2         Hopf Function:   1.83854E-01

   1     2         Eigenvalues  :   Stable:   0
   1     2         Eigenvalue  1:   1.83854E-01  -2.01209E+00
   1     2         Eigenvalue  2:   1.83854E-01   2.01209E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     2        0   2.02047E+00   3.37020E+00   2.02047E+00   2.69739E+00

   1     1         Iterations   :   2
   1     1         Next Step    :   3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     3   0        2.03586E+00   3.36299E+00
   1     3   1        2.03595E+00   3.36315E+00
   1     3   2        2.03595E+00   3.36315E+00
   1     3   3        2.03595E+00   3.36315E+00

   1     3         Fold Function:   5.17869E-01
   1     3         BP   Function:   1.60081E+01
   1     3         Hopf Function:   1.52455E-01

   1     3         Eigenvalues  :   Stable:   0
   1     3         Eigenvalue  1:   1.52455E-01  -2.03023E+00
   1     3         Eigenvalue  2:   1.52455E-01   2.03023E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     3        0   2.03595E+00   3.36315E+00   2.03595E+00   2.67688E+00

   1     2         Iterations   :   3
   1     2         Next Step    :   3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     4   0        2.05143E+00   3.35629E+00
   1     4   1        2.05154E+00   3.35649E+00
   1     4   2        2.05154E+00   3.35649E+00
   1     4   3        2.05154E+00   3.35649E+00

   1     4         Fold Function:   5.21515E-01
   1     4         BP   Function:   1.61406E+01
   1     4         Hopf Function:   1.20591E-01

   1     4         Eigenvalues  :   Stable:   0
   1     4         Eigenvalue  1:   1.20591E-01  -2.04799E+00
   1     4         Eigenvalue  2:   1.20591E-01   2.04799E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     4        0   2.05154E+00   3.35649E+00   2.05154E+00   2.65654E+00

   1     3         Iterations   :   3
   1     3         Next Step    :   3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     5   0        2.06713E+00   3.35001E+00
   1     5   1        2.06724E+00   3.35021E+00
   1     5   2        2.06724E+00   3.35021E+00
   1     5   3        2.06724E+00   3.35021E+00

   1     5         Fold Function:   5.25124E-01
   1     5         BP   Function:   1.62760E+01
   1     5         Hopf Function:   8.82592E-02

   1     5         Eigenvalues  :   Stable:   0
   1     5         Eigenvalue  1:   8.82592E-02  -2.06536E+00
   1     5         Eigenvalue  2:   8.82592E-02   2.06536E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     5        0   2.06724E+00   3.35021E+00   2.06724E+00   2.63637E+00

   1     4         Iterations   :   3
   1     4         Next Step    :   3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     6   0        2.08294E+00   3.34411E+00
   1     6   1        2.08305E+00   3.34431E+00
   1     6   2        2.08305E+00   3.34431E+00
   1     6   3        2.08305E+00   3.34431E+00

   1     6         Fold Function:   5.28694E-01
   1     6         BP   Function:   1.64142E+01
   1     6         Hopf Function:   5.54566E-02

   1     6         Eigenvalues  :   Stable:   0
   1     6         Eigenvalue  1:   5.54566E-02  -2.08231E+00
   1     6         Eigenvalue  2:   5.54566E-02   2.08231E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     6        0   2.08305E+00   3.34431E+00   2.08305E+00   2.61636E+00

   1     5         Iterations   :   3
   1     5         Next Step    :   3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     7   0        2.09885E+00   3.33860E+00
   1     7   1        2.09896E+00   3.33880E+00
   1     7   2        2.09896E+00   3.33880E+00
   1     7   3        2.09896E+00   3.33880E+00

   1     7         Fold Function:   5.32224E-01
   1     7         BP   Function:   1.65555E+01
   1     7         Hopf Function:   2.21806E-02

   1     7         Eigenvalues  :   Stable:   0
   1     7         Eigenvalue  1:   2.21806E-02  -2.09884E+00
   1     7         Eigenvalue  2:   2.21806E-02   2.09884E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     7        0   2.09896E+00   3.33880E+00   2.09896E+00   2.59652E+00

   1     6         Iterations   :   3
   1     6         Next Step    :   3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     8   0        2.11488E+00   3.33347E+00
   1     8   1        2.11498E+00   3.33367E+00
   1     8   2        2.11498E+00   3.33367E+00
   1     8   3        2.11498E+00   3.33367E+00

   1     8         Fold Function:   5.35713E-01
   1     8         BP   Function:   1.66996E+01
   1     8         Hopf Function:  -1.15714E-02

   1     8         Eigenvalues  :   Stable:   2
   1     8         Eigenvalue  1:  -1.15714E-02  -2.11495E+00
   1     8         Eigenvalue  2:  -1.15714E-02   2.11495E+00
 ==> Location of special point :  Iteration   0  Step size =  -1.02851E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     8   0        2.10949E+00   3.33540E+00
   1     8   1        2.10948E+00   3.33538E+00
   1     8   2        2.10948E+00   3.33538E+00

   1     8         Hopf Function:   5.37443E-05

   1     8         Eigenvalues  :   Stable:   0
   1     8         Eigenvalue  1:   5.37443E-05  -2.10948E+00
   1     8         Eigenvalue  2:   5.37443E-05   2.10948E+00
 ==> Location of special point :  Iteration   1  Step size =   4.76635E-05
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     8   0        2.10950E+00   3.33537E+00
   1     8   1        2.10950E+00   3.33537E+00

   1     8         Hopf Function:   2.47849E-09

   1     8         Eigenvalues  :   Stable:   2
   1     8         Eigenvalue  1:   2.47849E-09  -2.10950E+00
   1     8         Eigenvalue  2:   2.47849E-09   2.10950E+00
 ==> Location of special point :  Convergence.   Step size =   2.19814E-09
   1     8         Fold Function:   5.34527E-01
   1     8         BP   Function:   1.66502E+01

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     8  HB    2   2.10950E+00   3.33537E+00   2.10950E+00   2.58355E+00
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     9   0        2.12554E+00   3.33040E+00
   1     9   1        2.12559E+00   3.33050E+00
   1     9   2        2.12559E+00   3.33050E+00

   1     9         Fold Function:   5.37989E-01
   1     9         BP   Function:   1.67964E+01
   1     9         Hopf Function:  -3.40669E-02

   1     9         Eigenvalues  :   Stable:   2
   1     9         Eigenvalue  1:  -3.40669E-02  -2.12532E+00
   1     9         Eigenvalue  2:  -3.40669E-02   2.12532E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    -9        0   2.12559E+00   3.33050E+00   2.12559E+00   2.56399E+00

   1     8         Iterations   :   2
   1     8         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    10   0        2.14972E+00   3.32353E+00
   1    10   1        2.14992E+00   3.32389E+00
   1    10   2        2.14992E+00   3.32389E+00
   1    10   3        2.14992E+00   3.32389E+00

   1    10         Fold Function:   5.43102E-01
   1    10         BP   Function:   1.70210E+01
   1    10         Hopf Function:  -8.60678E-02

   1    10         Eigenvalues  :   Stable:   2
   1    10         Eigenvalue  1:  -8.60678E-02  -2.14819E+00
   1    10         Eigenvalue  2:  -8.60678E-02   2.14819E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -10        0   2.14992E+00   3.32389E+00   2.14992E+00   2.53498E+00

   1     9         Iterations   :   3
   1     9         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    11   0        2.17424E+00   3.31771E+00
   1    11   1        2.17447E+00   3.31815E+00
   1    11   2        2.17447E+00   3.31815E+00
   1    11   3        2.17447E+00   3.31815E+00

   1    11         Fold Function:   5.48115E-01
   1    11         BP   Function:   1.72527E+01
   1    11         Hopf Function:  -1.39156E-01

   1    11         Eigenvalues  :   Stable:   2
   1    11         Eigenvalue  1:  -1.39156E-01  -2.17001E+00
   1    11         Eigenvalue  2:  -1.39156E-01   2.17001E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -11        0   2.17447E+00   3.31815E+00   2.17447E+00   2.50636E+00

   1    10         Iterations   :   3
   1    10         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    12   0        2.19902E+00   3.31283E+00
   1    12   1        2.19925E+00   3.31327E+00
   1    12   2        2.19924E+00   3.31327E+00
   1    12   3        2.19924E+00   3.31327E+00

   1    12         Fold Function:   5.53027E-01
   1    12         BP   Function:   1.74914E+01
   1    12         Hopf Function:  -1.93338E-01

   1    12         Eigenvalues  :   Stable:   2
   1    12         Eigenvalue  1:  -1.93338E-01  -2.19073E+00
   1    12         Eigenvalue  2:  -1.93338E-01   2.19073E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -12        0   2.19924E+00   3.31327E+00   2.19924E+00   2.47812E+00

   1    11         Iterations   :   3
   1    11         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    13   0        2.22402E+00   3.30881E+00
   1    13   1        2.22424E+00   3.30924E+00
   1    13   2        2.22424E+00   3.30924E+00
   1    13   3        2.22424E+00   3.30924E+00

   1    13         Fold Function:   5.57835E-01
   1    13         BP   Function:   1.77370E+01
   1    13         Hopf Function:  -2.48620E-01

   1    13         Eigenvalues  :   Stable:   2
   1    13         Eigenvalue  1:  -2.48620E-01  -2.21030E+00
   1    13         Eigenvalue  2:  -2.48620E-01   2.21030E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -13        0   2.22424E+00   3.30924E+00   2.22424E+00   2.45028E+00

   1    12         Iterations   :   3
   1    12         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    14   0        2.24923E+00   3.30563E+00
   1    14   1        2.24945E+00   3.30606E+00
   1    14   2        2.24945E+00   3.30606E+00
   1    14   3        2.24945E+00   3.30606E+00

   1    14         Fold Function:   5.62537E-01
   1    14         BP   Function:   1.79897E+01
   1    14         Hopf Function:  -3.05008E-01

   1    14         Eigenvalues  :   Stable:   2
   1    14         Eigenvalue  1:  -3.05008E-01  -2.22867E+00
   1    14         Eigenvalue  2:  -3.05008E-01   2.22867E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -14        0   2.24945E+00   3.30606E+00   2.24945E+00   2.42282E+00

   1    13         Iterations   :   3
   1    13         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    15   0        2.27466E+00   3.30330E+00
   1    15   1        2.27487E+00   3.30373E+00
   1    15   2        2.27487E+00   3.30373E+00
   1    15   3        2.27487E+00   3.30373E+00

   1    15         Fold Function:   5.67130E-01
   1    15         BP   Function:   1.82496E+01
   1    15         Hopf Function:  -3.62508E-01

   1    15         Eigenvalues  :   Stable:   2
   1    15         Eigenvalue  1:  -3.62508E-01  -2.24580E+00
   1    15         Eigenvalue  2:  -3.62508E-01   2.24580E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -15        0   2.27487E+00   3.30373E+00   2.27487E+00   2.39575E+00

   1    14         Iterations   :   3
   1    14         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    16   0        2.30028E+00   3.30181E+00
   1    16   1        2.30049E+00   3.30223E+00
   1    16   2        2.30049E+00   3.30223E+00
   1    16   3        2.30049E+00   3.30223E+00

   1    16         Fold Function:   5.71615E-01
   1    16         BP   Function:   1.85166E+01
   1    16         Hopf Function:  -4.21124E-01

   1    16         Eigenvalues  :   Stable:   2
   1    16         Eigenvalue  1:  -4.21124E-01  -2.26161E+00
   1    16         Eigenvalue  2:  -4.21124E-01   2.26161E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -16        0   2.30049E+00   3.30223E+00   2.30049E+00   2.36906E+00

   1    15         Iterations   :   3
   1    15         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    17   0        2.32611E+00   3.30114E+00
   1    17   1        2.32631E+00   3.30156E+00
   1    17   2        2.32631E+00   3.30156E+00
   1    17   3        2.32631E+00   3.30156E+00

   1    17         Fold Function:   5.75989E-01
   1    17         BP   Function:   1.87908E+01
   1    17         Hopf Function:  -4.80859E-01

   1    17         Eigenvalues  :   Stable:   2
   1    17         Eigenvalue  1:  -4.80859E-01  -2.27607E+00
   1    17         Eigenvalue  2:  -4.80859E-01   2.27607E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -17        0   2.32631E+00   3.30156E+00   2.32631E+00   2.34277E+00

   1    16         Iterations   :   3
   1    16         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    18   0        2.35213E+00   3.30130E+00
   1    18   1        2.35233E+00   3.30171E+00
   1    18   2        2.35233E+00   3.30171E+00
   1    18   3        2.35233E+00   3.30171E+00

   1    18         Fold Function:   5.80252E-01
   1    18         BP   Function:   1.90723E+01
   1    18         Hopf Function:  -5.41719E-01

   1    18         Eigenvalues  :   Stable:   2
   1    18         Eigenvalue  1:  -5.41719E-01  -2.28910E+00
   1    18         Eigenvalue  2:  -5.41719E-01   2.28910E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -18        0   2.35233E+00   3.30171E+00   2.35233E+00   2.31686E+00

   1    17         Iterations   :   3
   1    17         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    19   0        2.37834E+00   3.30226E+00
   1    19   1        2.37853E+00   3.30267E+00
   1    19   2        2.37853E+00   3.30267E+00
   1    19   3        2.37853E+00   3.30267E+00

   1    19         Fold Function:   5.84404E-01
   1    19         BP   Function:   1.93611E+01
   1    19         Hopf Function:  -6.03706E-01

   1    19         Eigenvalues  :   Stable:   2
   1    19         Eigenvalue  1:  -6.03706E-01  -2.30064E+00
   1    19         Eigenvalue  2:  -6.03706E-01   2.30064E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -19        0   2.37853E+00   3.30267E+00   2.37853E+00   2.29133E+00

   1    18         Iterations   :   3
   1    18         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    20   0        2.40474E+00   3.30403E+00
   1    20   1        2.40492E+00   3.30443E+00
   1    20   2        2.40492E+00   3.30443E+00
   1    20   3        2.40492E+00   3.30443E+00

   1    20         Fold Function:   5.88444E-01
   1    20         BP   Function:   1.96572E+01
   1    20         Hopf Function:  -6.66822E-01

   1    20         Eigenvalues  :   Stable:   2
   1    20         Eigenvalue  1:  -6.66822E-01  -2.31063E+00
   1    20         Eigenvalue  2:  -6.66822E-01   2.31063E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -20        0   2.40492E+00   3.30443E+00   2.40492E+00   2.26619E+00

   1    19         Iterations   :   3
   1    19         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    21   0        2.43131E+00   3.30659E+00
   1    21   1        2.43149E+00   3.30698E+00
   1    21   2        2.43149E+00   3.30698E+00
   1    21   3        2.43149E+00   3.30698E+00

   1    21         Fold Function:   5.92372E-01
   1    21         BP   Function:   1.99606E+01
   1    21         Hopf Function:  -7.31071E-01

   1    21         Eigenvalues  :   Stable:   2
   1    21         Eigenvalue  1:  -7.31071E-01  -2.31898E+00
   1    21         Eigenvalue  2:  -7.31071E-01   2.31898E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -21        0   2.43149E+00   3.30698E+00   2.43149E+00   2.24142E+00

   1    20         Iterations   :   3
   1    20         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    22   0        2.45806E+00   3.30993E+00
   1    22   1        2.45823E+00   3.31031E+00
   1    22   2        2.45823E+00   3.31031E+00
   1    22   3        2.45823E+00   3.31031E+00

   1    22         Fold Function:   5.96190E-01
   1    22         BP   Function:   2.02715E+01
   1    22         Hopf Function:  -7.96455E-01

   1    22         Eigenvalues  :   Stable:   2
   1    22         Eigenvalue  1:  -7.96455E-01  -2.32563E+00
   1    22         Eigenvalue  2:  -7.96455E-01   2.32563E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -22        0   2.45823E+00   3.31031E+00   2.45823E+00   2.21704E+00

   1    21         Iterations   :   3
   1    21         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    23   0        2.48498E+00   3.31404E+00
   1    23   1        2.48515E+00   3.31441E+00
   1    23   2        2.48515E+00   3.31441E+00
   1    23   3        2.48515E+00   3.31441E+00

   1    23         Fold Function:   5.99897E-01
   1    23         BP   Function:   2.05898E+01
   1    23         Hopf Function:  -8.62974E-01

   1    23         Eigenvalues  :   Stable:   2
   1    23         Eigenvalue  1:  -8.62974E-01  -2.33050E+00
   1    23         Eigenvalue  2:  -8.62974E-01   2.33050E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -23        0   2.48515E+00   3.31441E+00   2.48515E+00   2.19303E+00

   1    22         Iterations   :   3
   1    22         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    24   0        2.51206E+00   3.31890E+00
   1    24   1        2.51222E+00   3.31927E+00
   1    24   2        2.51222E+00   3.31927E+00
   1    24   3        2.51222E+00   3.31927E+00

   1    24         Fold Function:   6.03495E-01
   1    24         BP   Function:   2.09154E+01
   1    24         Hopf Function:  -9.30631E-01

   1    24         Eigenvalues  :   Stable:   2
   1    24         Eigenvalue  1:  -9.30631E-01  -2.33349E+00
   1    24         Eigenvalue  2:  -9.30631E-01   2.33349E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -24        0   2.51222E+00   3.31927E+00   2.51222E+00   2.16939E+00

   1    23         Iterations   :   3
   1    23         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    25   0        2.53930E+00   3.32450E+00
   1    25   1        2.53946E+00   3.32486E+00
   1    25   2        2.53946E+00   3.32486E+00
   1    25   3        2.53946E+00   3.32486E+00

   1    25         Fold Function:   6.06985E-01
   1    25         BP   Function:   2.12486E+01
   1    25         Hopf Function:  -9.99425E-01

   1    25         Eigenvalues  :   Stable:   2
   1    25         Eigenvalue  1:  -9.99425E-01  -2.33452E+00
   1    25         Eigenvalue  2:  -9.99425E-01   2.33452E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -25        0   2.53946E+00   3.32486E+00   2.53946E+00   2.14613E+00

   1    24         Iterations   :   3
   1    24         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    26   0        2.56669E+00   3.33083E+00
   1    26   1        2.56685E+00   3.33119E+00
   1    26   2        2.56685E+00   3.33119E+00
   1    26   3        2.56685E+00   3.33119E+00

   1    26         Fold Function:   6.10368E-01
   1    26         BP   Function:   2.15891E+01
   1    26         Hopf Function:  -1.06936E+00

   1    26         Eigenvalues  :   Stable:   2
   1    26         Eigenvalue  1:  -1.06936E+00  -2.33349E+00
   1    26         Eigenvalue  2:  -1.06936E+00   2.33349E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -26        0   2.56685E+00   3.33119E+00   2.56685E+00   2.12323E+00

   1    25         Iterations   :   3
   1    25         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    27   0        2.59424E+00   3.33788E+00
   1    27   1        2.59439E+00   3.33822E+00
   1    27   2        2.59439E+00   3.33822E+00
   1    27   3        2.59439E+00   3.33822E+00

   1    27         Fold Function:   6.13645E-01
   1    27         BP   Function:   2.19371E+01
   1    27         Hopf Function:  -1.14043E+00

   1    27         Eigenvalues  :   Stable:   2
   1    27         Eigenvalue  1:  -1.14043E+00  -2.33030E+00
   1    27         Eigenvalue  2:  -1.14043E+00   2.33030E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -27        0   2.59439E+00   3.33822E+00   2.59439E+00   2.10069E+00

   1    26         Iterations   :   3
   1    26         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    28   0        2.62193E+00   3.34563E+00
   1    28   1        2.62208E+00   3.34596E+00
   1    28   2        2.62208E+00   3.34596E+00
   1    28   3        2.62208E+00   3.34596E+00

   1    28         Fold Function:   6.16818E-01
   1    28         BP   Function:   2.22925E+01
   1    28         Hopf Function:  -1.21264E+00

   1    28         Eigenvalues  :   Stable:   2
   1    28         Eigenvalue  1:  -1.21264E+00  -2.32482E+00
   1    28         Eigenvalue  2:  -1.21264E+00   2.32482E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -28        0   2.62208E+00   3.34596E+00   2.62208E+00   2.07851E+00

   1    27         Iterations   :   3
   1    27         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    29   0        2.64976E+00   3.35406E+00
   1    29   1        2.64990E+00   3.35439E+00
   1    29   2        2.64990E+00   3.35439E+00
   1    29   3        2.64990E+00   3.35439E+00

   1    29         Fold Function:   6.19890E-01
   1    29         BP   Function:   2.26554E+01
   1    29         Hopf Function:  -1.28599E+00

   1    29         Eigenvalues  :   Stable:   2
   1    29         Eigenvalue  1:  -1.28599E+00  -2.31694E+00
   1    29         Eigenvalue  2:  -1.28599E+00   2.31694E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -29        0   2.64990E+00   3.35439E+00   2.64990E+00   2.05668E+00

   1    28         Iterations   :   3
   1    28         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    30   0        2.67773E+00   3.36316E+00
   1    30   1        2.67787E+00   3.36348E+00
   1    30   2        2.67787E+00   3.36348E+00
   1    30   3        2.67787E+00   3.36348E+00

   1    30         Fold Function:   6.22861E-01
   1    30         BP   Function:   2.30257E+01
   1    30         Hopf Function:  -1.36048E+00

   1    30         Eigenvalues  :   Stable:   2
   1    30         Eigenvalue  1:  -1.36048E+00  -2.30652E+00
   1    30         Eigenvalue  2:  -1.36048E+00   2.30652E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -30        0   2.67787E+00   3.36348E+00   2.67787E+00   2.03520E+00

   1    29         Iterations   :   3
   1    29         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    31   0        2.70583E+00   3.37292E+00
   1    31   1        2.70596E+00   3.37323E+00
   1    31   2        2.70596E+00   3.37323E+00
   1    31   3        2.70596E+00   3.37323E+00

   1    31         Fold Function:   6.25734E-01
   1    31         BP   Function:   2.34034E+01
   1    31         Hopf Function:  -1.43611E+00

   1    31         Eigenvalues  :   Stable:   2
   1    31         Eigenvalue  1:  -1.43611E+00  -2.29343E+00
   1    31         Eigenvalue  2:  -1.43611E+00   2.29343E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -31        0   2.70596E+00   3.37323E+00   2.70596E+00   2.01407E+00

   1    30         Iterations   :   3
   1    30         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    32   0        2.73405E+00   3.38332E+00
   1    32   1        2.73418E+00   3.38363E+00
   1    32   2        2.73418E+00   3.38363E+00
   1    32   3        2.73418E+00   3.38363E+00

   1    32         Fold Function:   6.28511E-01
   1    32         BP   Function:   2.37885E+01
   1    32         Hopf Function:  -1.51287E+00

   1    32         Eigenvalues  :   Stable:   2
   1    32         Eigenvalue  1:  -1.51287E+00  -2.27749E+00
   1    32         Eigenvalue  2:  -1.51287E+00   2.27749E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -32        0   2.73418E+00   3.38363E+00   2.73418E+00   1.99329E+00

   1    31         Iterations   :   3
   1    31         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    33   0        2.76240E+00   3.39435E+00
   1    33   1        2.76252E+00   3.39464E+00
   1    33   2        2.76252E+00   3.39464E+00
   1    33   3        2.76252E+00   3.39464E+00

   1    33         Fold Function:   6.31195E-01
   1    33         BP   Function:   2.41810E+01
   1    33         Hopf Function:  -1.59077E+00

   1    33         Eigenvalues  :   Stable:   2
   1    33         Eigenvalue  1:  -1.59077E+00  -2.25854E+00
   1    33         Eigenvalue  2:  -1.59077E+00   2.25854E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -33        0   2.76252E+00   3.39464E+00   2.76252E+00   1.97283E+00

   1    32         Iterations   :   3
   1    32         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    34   0        2.79087E+00   3.40599E+00
   1    34   1        2.79099E+00   3.40627E+00
   1    34   2        2.79099E+00   3.40627E+00
   1    34   3        2.79099E+00   3.40627E+00

   1    34         Fold Function:   6.33787E-01
   1    34         BP   Function:   2.45810E+01
   1    34         Hopf Function:  -1.66980E+00

   1    34         Eigenvalues  :   Stable:   2
   1    34         Eigenvalue  1:  -1.66980E+00  -2.23637E+00
   1    34         Eigenvalue  2:  -1.66980E+00   2.23637E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -34        0   2.79099E+00   3.40627E+00   2.79099E+00   1.95271E+00

   1    33         Iterations   :   3
   1    33         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    35   0        2.81945E+00   3.41822E+00
   1    35   1        2.81956E+00   3.41850E+00
   1    35   2        2.81956E+00   3.41850E+00
   1    35   3        2.81956E+00   3.41850E+00

   1    35         Fold Function:   6.36289E-01
   1    35         BP   Function:   2.49882E+01
   1    35         Hopf Function:  -1.74997E+00

   1    35         Eigenvalues  :   Stable:   2
   1    35         Eigenvalue  1:  -1.74997E+00  -2.21078E+00
   1    35         Eigenvalue  2:  -1.74997E+00   2.21078E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -35        0   2.81956E+00   3.41850E+00   2.81956E+00   1.93292E+00

   1    34         Iterations   :   3
   1    34         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    36   0        2.84814E+00   3.43103E+00
   1    36   1        2.84825E+00   3.43130E+00
   1    36   2        2.84825E+00   3.43130E+00
   1    36   3        2.84825E+00   3.43130E+00

   1    36         Fold Function:   6.38705E-01
   1    36         BP   Function:   2.54029E+01
   1    36         Hopf Function:  -1.83127E+00

   1    36         Eigenvalues  :   Stable:   2
   1    36         Eigenvalue  1:  -1.83127E+00  -2.18151E+00
   1    36         Eigenvalue  2:  -1.83127E+00   2.18151E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -36        0   2.84825E+00   3.43130E+00   2.84825E+00   1.91345E+00

   1    35         Iterations   :   3
   1    35         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    37   0        2.87694E+00   3.44441E+00
   1    37   1        2.87705E+00   3.44467E+00
   1    37   2        2.87705E+00   3.44467E+00
   1    37   3        2.87705E+00   3.44467E+00

   1    37         Fold Function:   6.41037E-01
   1    37         BP   Function:   2.58248E+01
   1    37         Hopf Function:  -1.91370E+00

   1    37         Eigenvalues  :   Stable:   2
   1    37         Eigenvalue  1:  -1.91370E+00  -2.14829E+00
   1    37         Eigenvalue  2:  -1.91370E+00   2.14829E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -37        0   2.87705E+00   3.44467E+00   2.87705E+00   1.89430E+00

   1    36         Iterations   :   3
   1    36         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    38   0        2.90584E+00   3.45834E+00
   1    38   1        2.90594E+00   3.45860E+00
   1    38   2        2.90594E+00   3.45860E+00
   1    38   3        2.90594E+00   3.45860E+00

   1    38         Fold Function:   6.43286E-01
   1    38         BP   Function:   2.62541E+01
   1    38         Hopf Function:  -1.99725E+00

   1    38         Eigenvalues  :   Stable:   2
   1    38         Eigenvalue  1:  -1.99725E+00  -2.11080E+00
   1    38         Eigenvalue  2:  -1.99725E+00   2.11080E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -38        0   2.90594E+00   3.45860E+00   2.90594E+00   1.87547E+00

   1    37         Iterations   :   3
   1    37         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    39   0        2.93484E+00   3.47280E+00
   1    39   1        2.93494E+00   3.47305E+00
   1    39   2        2.93494E+00   3.47305E+00
   1    39   3        2.93494E+00   3.47305E+00

   1    39         Fold Function:   6.45456E-01
   1    39         BP   Function:   2.66907E+01
   1    39         Hopf Function:  -2.08194E+00

   1    39         Eigenvalues  :   Stable:   2
   1    39         Eigenvalue  1:  -2.08194E+00  -2.06867E+00
   1    39         Eigenvalue  2:  -2.08194E+00   2.06867E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -39        0   2.93494E+00   3.47305E+00   2.93494E+00   1.85694E+00

   1    38         Iterations   :   3
   1    38         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    40   0        2.96394E+00   3.48779E+00
   1    40   1        2.96403E+00   3.48803E+00
   1    40   2        2.96403E+00   3.48803E+00
   1    40   3        2.96403E+00   3.48803E+00

   1    40         Fold Function:   6.47548E-01
   1    40         BP   Function:   2.71345E+01
   1    40         Hopf Function:  -2.16775E+00

   1    40         Eigenvalues  :   Stable:   2
   1    40         Eigenvalue  1:  -2.16775E+00  -2.02148E+00
   1    40         Eigenvalue  2:  -2.16775E+00   2.02148E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -40        0   2.96403E+00   3.48803E+00   2.96403E+00   1.83871E+00

   1    39         Iterations   :   3
   1    39         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    41   0        2.99313E+00   3.50328E+00
   1    41   1        2.99322E+00   3.50351E+00
   1    41   2        2.99322E+00   3.50351E+00
   1    41   3        2.99322E+00   3.50351E+00

   1    41         Fold Function:   6.49565E-01
   1    41         BP   Function:   2.75855E+01
   1    41         Hopf Function:  -2.25468E+00

   1    41         Eigenvalues  :   Stable:   2
   1    41         Eigenvalue  1:  -2.25468E+00  -1.96870E+00
   1    41         Eigenvalue  2:  -2.25468E+00   1.96870E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -41        0   2.99322E+00   3.50351E+00   2.99322E+00   1.82078E+00

   1    40         Iterations   :   3
   1    40         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    42   0        3.02240E+00   3.51926E+00
   1    42   1        3.02249E+00   3.51949E+00
   1    42   2        3.02249E+00   3.51949E+00
   1    42   3        3.02249E+00   3.51949E+00

   1    42         Fold Function:   6.51510E-01
   1    42         BP   Function:   2.80438E+01
   1    42         Hopf Function:  -2.34273E+00

   1    42         Eigenvalues  :   Stable:   2
   1    42         Eigenvalue  1:  -2.34273E+00  -1.90973E+00
   1    42         Eigenvalue  2:  -2.34273E+00   1.90973E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -42        0   3.02249E+00   3.51949E+00   3.02249E+00   1.80315E+00

   1    41         Iterations   :   3
   1    41         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    43   0        3.05177E+00   3.53572E+00
   1    43   1        3.05185E+00   3.53594E+00
   1    43   2        3.05185E+00   3.53594E+00
   1    43   3        3.05185E+00   3.53594E+00

   1    43         Fold Function:   6.53385E-01
   1    43         BP   Function:   2.85092E+01
   1    43         Hopf Function:  -2.43191E+00

   1    43         Eigenvalues  :   Stable:   2
   1    43         Eigenvalue  1:  -2.43191E+00  -1.84381E+00
   1    43         Eigenvalue  2:  -2.43191E+00   1.84381E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -43        0   3.05185E+00   3.53594E+00   3.05185E+00   1.78580E+00

   1    42         Iterations   :   3
   1    42         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    44   0        3.08121E+00   3.55265E+00
   1    44   1        3.08130E+00   3.55286E+00
   1    44   2        3.08130E+00   3.55286E+00
   1    44   3        3.08130E+00   3.55286E+00

   1    44         Fold Function:   6.55192E-01
   1    44         BP   Function:   2.89819E+01
   1    44         Hopf Function:  -2.52220E+00

   1    44         Eigenvalues  :   Stable:   2
   1    44         Eigenvalue  1:  -2.52220E+00  -1.77001E+00
   1    44         Eigenvalue  2:  -2.52220E+00   1.77001E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -44        0   3.08130E+00   3.55286E+00   3.08130E+00   1.76874E+00

   1    43         Iterations   :   3
   1    43         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    45   0        3.11074E+00   3.57002E+00
   1    45   1        3.11082E+00   3.57023E+00
   1    45   2        3.11082E+00   3.57023E+00
   1    45   3        3.11082E+00   3.57023E+00

   1    45         Fold Function:   6.56933E-01
   1    45         BP   Function:   2.94616E+01
   1    45         Hopf Function:  -2.61360E+00

   1    45         Eigenvalues  :   Stable:   2
   1    45         Eigenvalue  1:  -2.61360E+00  -1.68710E+00
   1    45         Eigenvalue  2:  -2.61360E+00   1.68710E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -45        0   3.11082E+00   3.57023E+00   3.11082E+00   1.75195E+00

   1    44         Iterations   :   3
   1    44         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    46   0        3.14034E+00   3.58783E+00
   1    46   1        3.14042E+00   3.58803E+00
   1    46   2        3.14042E+00   3.58803E+00
   1    46   3        3.14042E+00   3.58803E+00

   1    46         Fold Function:   6.58610E-01
   1    46         BP   Function:   2.99485E+01
   1    46         Hopf Function:  -2.70612E+00

   1    46         Eigenvalues  :   Stable:   2
   1    46         Eigenvalue  1:  -2.70612E+00  -1.59347E+00
   1    46         Eigenvalue  2:  -2.70612E+00   1.59347E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -46        0   3.14042E+00   3.58803E+00   3.14042E+00   1.73544E+00

   1    45         Iterations   :   3
   1    45         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    47   0        3.17002E+00   3.60607E+00
   1    47   1        3.17009E+00   3.60626E+00
   1    47   2        3.17009E+00   3.60626E+00
   1    47   3        3.17009E+00   3.60626E+00

   1    47         Fold Function:   6.60227E-01
   1    47         BP   Function:   3.04424E+01
   1    47         Hopf Function:  -2.79975E+00

   1    47         Eigenvalues  :   Stable:   2
   1    47         Eigenvalue  1:  -2.79975E+00  -1.48691E+00
   1    47         Eigenvalue  2:  -2.79975E+00   1.48691E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -47        0   3.17009E+00   3.60626E+00   3.17009E+00   1.71919E+00

   1    46         Iterations   :   3
   1    46         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    48   0        3.19977E+00   3.62471E+00
   1    48   1        3.19984E+00   3.62490E+00
   1    48   2        3.19984E+00   3.62490E+00
   1    48   3        3.19984E+00   3.62490E+00

   1    48         Fold Function:   6.61784E-01
   1    48         BP   Function:   3.09434E+01
   1    48         Hopf Function:  -2.89449E+00

   1    48         Eigenvalues  :   Stable:   2
   1    48         Eigenvalue  1:  -2.89449E+00  -1.36416E+00
   1    48         Eigenvalue  2:  -2.89449E+00   1.36416E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -48        0   3.19984E+00   3.62490E+00   3.19984E+00   1.70321E+00

   1    47         Iterations   :   3
   1    47         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    49   0        3.22959E+00   3.64376E+00
   1    49   1        3.22965E+00   3.64394E+00
   1    49   2        3.22965E+00   3.64394E+00
   1    49   3        3.22965E+00   3.64394E+00

   1    49         Fold Function:   6.63285E-01
   1    49         BP   Function:   3.14514E+01
   1    49         Hopf Function:  -2.99033E+00

   1    49         Eigenvalues  :   Stable:   2
   1    49         Eigenvalue  1:  -2.99033E+00  -1.22007E+00
   1    49         Eigenvalue  2:  -2.99033E+00   1.22007E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -49        0   3.22965E+00   3.64394E+00   3.22965E+00   1.68749E+00

   1    48         Iterations   :   3
   1    48         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    50   0        3.25947E+00   3.66319E+00
   1    50   1        3.25954E+00   3.66336E+00
   1    50   2        3.25953E+00   3.66336E+00
   1    50   3        3.25953E+00   3.66336E+00

   1    50         Fold Function:   6.64730E-01
   1    50         BP   Function:   3.19664E+01
   1    50         Hopf Function:  -3.08728E+00

   1    50         Eigenvalues  :   Stable:   2
   1    50         Eigenvalue  1:  -3.08728E+00  -1.04559E+00
   1    50         Eigenvalue  2:  -3.08728E+00   1.04559E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -50        0   3.25953E+00   3.66336E+00   3.25953E+00   1.67202E+00

   1    49         Iterations   :   3
   1    49         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    51   0        3.28942E+00   3.68299E+00
   1    51   1        3.28948E+00   3.68316E+00
   1    51   2        3.28948E+00   3.68316E+00
   1    51   3        3.28948E+00   3.68316E+00

   1    51         Fold Function:   6.66122E-01
   1    51         BP   Function:   3.24884E+01
   1    51         Hopf Function:  -3.18534E+00

   1    51         Eigenvalues  :   Stable:   2
   1    51         Eigenvalue  1:  -3.18534E+00  -8.21162E-01
   1    51         Eigenvalue  2:  -3.18534E+00   8.21162E-01

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -51        0   3.28948E+00   3.68316E+00   3.28948E+00   1.65680E+00

   1    50         Iterations   :   3
   1    50         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    52   0        3.31942E+00   3.70315E+00
   1    52   1        3.31949E+00   3.70332E+00
   1    52   2        3.31948E+00   3.70332E+00
   1    52   3        3.31948E+00   3.70332E+00

   1    52         Fold Function:   6.67464E-01
   1    52         BP   Function:   3.30173E+01
   1    52         Hopf Function:  -3.28449E+00

   1    52         Eigenvalues  :   Stable:   2
   1    52         Eigenvalue  1:  -3.28449E+00  -4.80734E-01
   1    52         Eigenvalue  2:  -3.28449E+00   4.80734E-01

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -52        0   3.31948E+00   3.70332E+00   3.31948E+00   1.64182E+00

   1    51         Iterations   :   3
   1    51         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    53   0        3.34949E+00   3.72367E+00
   1    53   1        3.34955E+00   3.72383E+00
   1    53   2        3.34955E+00   3.72383E+00
   1    53   3        3.34955E+00   3.72383E+00

   1    53         Fold Function:   6.68756E-01
   1    53         BP   Function:   3.35532E+01
   1    53         Hopf Function:   0.00000E+00

   1    53         Eigenvalues  :   Stable:   2
   1    53         Eigenvalue  1:  -2.89792E+00   0.00000E+00
   1    53         Eigenvalue  2:  -3.87157E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -53        0   3.34955E+00   3.72383E+00   3.34955E+00   1.62708E+00

   1    52         Iterations   :   3
   1    52         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    54   0        3.37962E+00   3.74452E+00
   1    54   1        3.37967E+00   3.74468E+00
   1    54   2        3.37967E+00   3.74468E+00
   1    54   3        3.37967E+00   3.74468E+00

   1    54         Fold Function:   6.70001E-01
   1    54         BP   Function:   3.40959E+01
   1    54         Hopf Function:   0.00000E+00

   1    54         Eigenvalues  :   Stable:   2
   1    54         Eigenvalue  1:  -2.63131E+00   0.00000E+00
   1    54         Eigenvalue  2:  -4.34088E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -54        0   3.37967E+00   3.74468E+00   3.37967E+00   1.61258E+00

   1    53         Iterations   :   3
   1    53         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    55   0        3.40979E+00   3.76571E+00
   1    55   1        3.40985E+00   3.76586E+00
   1    55   2        3.40985E+00   3.76586E+00
   1    55   3        3.40985E+00   3.76586E+00

   1    55         Fold Function:   6.71200E-01
   1    55         BP   Function:   3.46455E+01
   1    55         Hopf Function:   0.00000E+00

   1    55         Eigenvalues  :   Stable:   2
   1    55         Eigenvalue  1:  -2.47027E+00   0.00000E+00
   1    55         Eigenvalue  2:  -4.70680E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -55        0   3.40985E+00   3.76586E+00   3.40985E+00   1.59831E+00

   1    54         Iterations   :   3
   1    54         Next Step    :   4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    56   0        3.44003E+00   3.78721E+00
   1    56   1        3.44008E+00   3.78735E+00
   1    56   2        3.44008E+00   3.78735E+00

   1    56         Fold Function:   6.72355E-01
   1    56         BP   Function:   3.52025E+01
   1    56         Hopf Function:   0.00000E+00

   1    56         Eigenvalues  :   Stable:   2
   1    56         Eigenvalue  1:  -2.35145E+00   0.00000E+00
   1    56         Eigenvalue  2:  -5.03269E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -56        0   3.44008E+00   3.78735E+00   3.44008E+00   1.58427E+00

   1    55         Iterations   :   2
   1    55         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    57   0        3.48039E+00   3.81628E+00
   1    57   1        3.48047E+00   3.81649E+00
   1    57   2        3.48047E+00   3.81649E+00
   1    57   3        3.48047E+00   3.81649E+00

   1    57         Fold Function:   6.73830E-01
   1    57         BP   Function:   3.59544E+01
   1    57         Hopf Function:   0.00000E+00

   1    57         Eigenvalues  :   Stable:   2
   1    57         Eigenvalue  1:  -2.22895E+00   0.00000E+00
   1    57         Eigenvalue  2:  -5.43470E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -57        0   3.48047E+00   3.81649E+00   3.48047E+00   1.56588E+00

   1    56         Iterations   :   3
   1    56         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    58   0        3.52085E+00   3.84593E+00
   1    58   1        3.52094E+00   3.84616E+00
   1    58   2        3.52094E+00   3.84616E+00
   1    58   3        3.52094E+00   3.84616E+00

   1    58         Fold Function:   6.75234E-01
   1    58         BP   Function:   3.67189E+01
   1    58         Hopf Function:   0.00000E+00

   1    58         Eigenvalues  :   Stable:   2
   1    58         Eigenvalue  1:  -2.13184E+00   0.00000E+00
   1    58         Eigenvalue  2:  -5.81516E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -58        0   3.52094E+00   3.84616E+00   3.52094E+00   1.54788E+00

   1    57         Iterations   :   3
   1    57         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    59   0        3.56141E+00   3.87610E+00
   1    59   1        3.56149E+00   3.87633E+00
   1    59   2        3.56149E+00   3.87633E+00
   1    59   3        3.56149E+00   3.87633E+00

   1    59         Fold Function:   6.76570E-01
   1    59         BP   Function:   3.74955E+01
   1    59         Hopf Function:   0.00000E+00

   1    59         Eigenvalues  :   Stable:   2
   1    59         Eigenvalue  1:  -2.05159E+00   0.00000E+00
   1    59         Eigenvalue  2:  -6.18264E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -59        0   3.56149E+00   3.87633E+00   3.56149E+00   1.53026E+00

   1    58         Iterations   :   3
   1    58         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    60   0        3.60205E+00   3.90676E+00
   1    60   1        3.60213E+00   3.90698E+00
   1    60   2        3.60213E+00   3.90698E+00
   1    60   3        3.60213E+00   3.90698E+00

   1    60         Fold Function:   6.77842E-01
   1    60         BP   Function:   3.82840E+01
   1    60         Hopf Function:   0.00000E+00

   1    60         Eigenvalues  :   Stable:   2
   1    60         Eigenvalue  1:  -1.98342E+00   0.00000E+00
   1    60         Eigenvalue  2:  -6.54189E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -60        0   3.60213E+00   3.90698E+00   3.60213E+00   1.51300E+00

   1    59         Iterations   :   3
   1    59         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    61   0        3.64276E+00   3.93788E+00
   1    61   1        3.64283E+00   3.93809E+00
   1    61   2        3.64283E+00   3.93808E+00
   1    61   3        3.64283E+00   3.93808E+00

   1    61         Fold Function:   6.79052E-01
   1    61         BP   Function:   3.90844E+01
   1    61         Hopf Function:   0.00000E+00

   1    61         Eigenvalues  :   Stable:   2
   1    61         Eigenvalue  1:  -1.92438E+00   0.00000E+00
   1    61         Eigenvalue  2:  -6.89585E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -61        0   3.64283E+00   3.93808E+00   3.64283E+00   1.49609E+00

   1    60         Iterations   :   3
   1    60         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    62   0        3.68354E+00   3.96944E+00
   1    62   1        3.68361E+00   3.96963E+00
   1    62   2        3.68361E+00   3.96963E+00
   1    62   3        3.68361E+00   3.96963E+00

   1    62         Fold Function:   6.80205E-01
   1    62         BP   Function:   3.98966E+01
   1    62         Hopf Function:   0.00000E+00

   1    62         Eigenvalues  :   Stable:   2
   1    62         Eigenvalue  1:  -1.87249E+00   0.00000E+00
   1    62         Eigenvalue  2:  -7.24650E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -62        0   3.68361E+00   3.96963E+00   3.68361E+00   1.47953E+00

   1    61         Iterations   :   3
   1    61         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    63   0        3.72439E+00   4.00142E+00
   1    63   1        3.72446E+00   4.00160E+00
   1    63   2        3.72446E+00   4.00160E+00
   1    63   3        3.72446E+00   4.00160E+00

   1    63         Fold Function:   6.81303E-01
   1    63         BP   Function:   4.07205E+01
   1    63         Hopf Function:   0.00000E+00

   1    63         Eigenvalues  :   Stable:   2
   1    63         Eigenvalue  1:  -1.82636E+00   0.00000E+00
   1    63         Eigenvalue  2:  -7.59522E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -63        0   3.72446E+00   4.00160E+00   3.72446E+00   1.46330E+00

   1    62         Iterations   :   3
   1    62         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    64   0        3.76530E+00   4.03380E+00
   1    64   1        3.76537E+00   4.03398E+00
   1    64   2        3.76537E+00   4.03398E+00
   1    64   3        3.76537E+00   4.03398E+00

   1    64         Fold Function:   6.82349E-01
   1    64         BP   Function:   4.15562E+01
   1    64         Hopf Function:   0.00000E+00

   1    64         Eigenvalues  :   Stable:   2
   1    64         Eigenvalue  1:  -1.78496E+00   0.00000E+00
   1    64         Eigenvalue  2:  -7.94302E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -64        0   3.76537E+00   4.03398E+00   3.76537E+00   1.44740E+00

   1    63         Iterations   :   3
   1    63         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    65   0        3.80628E+00   4.06656E+00
   1    65   1        3.80634E+00   4.06673E+00
   1    65   2        3.80634E+00   4.06673E+00
   1    65   3        3.80634E+00   4.06673E+00

   1    65         Fold Function:   6.83346E-01
   1    65         BP   Function:   4.24035E+01
   1    65         Hopf Function:   0.00000E+00

   1    65         Eigenvalues  :   Stable:   2
   1    65         Eigenvalue  1:  -1.74753E+00   0.00000E+00
   1    65         Eigenvalue  2:  -8.29067E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -65        0   3.80634E+00   4.06673E+00   3.80634E+00   1.43182E+00

   1    64         Iterations   :   3
   1    64         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    66   0        3.84731E+00   4.09970E+00
   1    66   1        3.84737E+00   4.09986E+00
   1    66   2        3.84737E+00   4.09986E+00
   1    66   3        3.84737E+00   4.09986E+00

   1    66         Fold Function:   6.84296E-01
   1    66         BP   Function:   4.32625E+01
   1    66         Hopf Function:   0.00000E+00

   1    66         Eigenvalues  :   Stable:   2
   1    66         Eigenvalue  1:  -1.71347E+00   0.00000E+00
   1    66         Eigenvalue  2:  -8.63876E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -66        0   3.84737E+00   4.09986E+00   3.84737E+00   1.41655E+00

   1    65         Iterations   :   3
   1    65         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    67   0        3.88840E+00   4.13319E+00
   1    67   1        3.88845E+00   4.13334E+00
   1    67   2        3.88845E+00   4.13334E+00
   1    67   3        3.88845E+00   4.13334E+00

   1    67         Fold Function:   6.85201E-01
   1    67         BP   Function:   4.41331E+01
   1    67         Hopf Function:   0.00000E+00

   1    67         Eigenvalues  :   Stable:   2
   1    67         Eigenvalue  1:  -1.68229E+00   0.00000E+00
   1    67         Eigenvalue  2:  -8.98776E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -67        0   3.88845E+00   4.13334E+00   3.88845E+00   1.40159E+00

   1    66         Iterations   :   3
   1    66         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    68   0        3.92954E+00   4.16701E+00
   1    68   1        3.92959E+00   4.16716E+00
   1    68   2        3.92959E+00   4.16716E+00
   1    68   3        3.92959E+00   4.16716E+00

   1    68         Fold Function:   6.86064E-01
   1    68         BP   Function:   4.50151E+01
   1    68         Hopf Function:   0.00000E+00

   1    68         Eigenvalues  :   Stable:   2
   1    68         Eigenvalue  1:  -1.65363E+00   0.00000E+00
   1    68         Eigenvalue  2:  -9.33805E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -68        0   3.92959E+00   4.16716E+00   3.92959E+00   1.38691E+00

   1    67         Iterations   :   3
   1    67         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    69   0        3.97073E+00   4.20116E+00
   1    69   1        3.97078E+00   4.20130E+00
   1    69   2        3.97078E+00   4.20130E+00
   1    69   3        3.97078E+00   4.20130E+00

   1    69         Fold Function:   6.86887E-01
   1    69         BP   Function:   4.59087E+01
   1    69         Hopf Function:   0.00000E+00

   1    69         Eigenvalues  :   Stable:   2
   1    69         Eigenvalue  1:  -1.62716E+00   0.00000E+00
   1    69         Eigenvalue  2:  -9.68992E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -69        0   3.97078E+00   4.20130E+00   3.97078E+00   1.37253E+00

   1    68         Iterations   :   3
   1    68         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    70   0        4.01197E+00   4.23561E+00
   1    70   1        4.01202E+00   4.23575E+00
   1    70   2        4.01202E+00   4.23575E+00

   1    70         Fold Function:   6.87672E-01
   1    70         BP   Function:   4.68142E+01
   1    70         Hopf Function:   0.00000E+00

   1    70         Eigenvalues  :   Stable:   2
   1    70         Eigenvalue  1:  -1.60263E+00   0.00000E+00
   1    70         Eigenvalue  2:  -1.00436E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -70        0   4.01202E+00   4.23575E+00   4.01202E+00   1.35842E+00

   1    69         Iterations   :   2
   1    69         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    71   0        4.05325E+00   4.27037E+00
   1    71   1        4.05330E+00   4.27050E+00
   1    71   2        4.05330E+00   4.27050E+00

   1    71         Fold Function:   6.88422E-01
   1    71         BP   Function:   4.77306E+01
   1    71         Hopf Function:   0.00000E+00

   1    71         Eigenvalues  :   Stable:   2
   1    71         Eigenvalue  1:  -1.57982E+00   0.00000E+00
   1    71         Eigenvalue  2:  -1.03994E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -71        0   4.05330E+00   4.27050E+00   4.05330E+00   1.34458E+00

   1    70         Iterations   :   2
   1    70         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    72   0        4.09458E+00   4.30540E+00
   1    72   1        4.09463E+00   4.30553E+00
   1    72   2        4.09463E+00   4.30553E+00

   1    72         Fold Function:   6.89136E-01
   1    72         BP   Function:   4.86583E+01
   1    72         Hopf Function:   0.00000E+00

   1    72         Eigenvalues  :   Stable:   2
   1    72         Eigenvalue  1:  -1.55855E+00   0.00000E+00
   1    72         Eigenvalue  2:  -1.07574E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -72        0   4.09463E+00   4.30553E+00   4.09463E+00   1.33101E+00

   1    71         Iterations   :   2
   1    71         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    73   0        4.13595E+00   4.34071E+00
   1    73   1        4.13600E+00   4.34083E+00
   1    73   2        4.13599E+00   4.34083E+00

   1    73         Fold Function:   6.89819E-01
   1    73         BP   Function:   4.95973E+01
   1    73         Hopf Function:   0.00000E+00

   1    73         Eigenvalues  :   Stable:   2
   1    73         Eigenvalue  1:  -1.53865E+00   0.00000E+00
   1    73         Eigenvalue  2:  -1.11178E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -73        0   4.13599E+00   4.34083E+00   4.13599E+00   1.31770E+00

   1    72         Iterations   :   2
   1    72         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    74   0        4.17736E+00   4.37628E+00
   1    74   1        4.17740E+00   4.37639E+00
   1    74   2        4.17740E+00   4.37639E+00

   1    74         Fold Function:   6.90471E-01
   1    74         BP   Function:   5.05476E+01
   1    74         Hopf Function:   0.00000E+00

   1    74         Eigenvalues  :   Stable:   2
   1    74         Eigenvalue  1:  -1.52000E+00   0.00000E+00
   1    74         Eigenvalue  2:  -1.14807E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -74        0   4.17740E+00   4.37639E+00   4.17740E+00   1.30464E+00

   1    73         Iterations   :   2
   1    73         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    75   0        4.21881E+00   4.41209E+00
   1    75   1        4.21885E+00   4.41220E+00
   1    75   2        4.21885E+00   4.41220E+00

   1    75         Fold Function:   6.91093E-01
   1    75         BP   Function:   5.15092E+01
   1    75         Hopf Function:   0.00000E+00

   1    75         Eigenvalues  :   Stable:   2
   1    75         Eigenvalue  1:  -1.50248E+00   0.00000E+00
   1    75         Eigenvalue  2:  -1.18462E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -75        0   4.21885E+00   4.41220E+00   4.21885E+00   1.29182E+00

   1    74         Iterations   :   2
   1    74         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    76   0        4.26030E+00   4.44814E+00
   1    76   1        4.26033E+00   4.44825E+00
   1    76   2        4.26033E+00   4.44825E+00

   1    76         Fold Function:   6.91688E-01
   1    76         BP   Function:   5.24820E+01
   1    76         Hopf Function:   0.00000E+00

   1    76         Eigenvalues  :   Stable:   2
   1    76         Eigenvalue  1:  -1.48598E+00   0.00000E+00
   1    76         Eigenvalue  2:  -1.22145E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -76        0   4.26033E+00   4.44825E+00   4.26033E+00   1.27924E+00

   1    75         Iterations   :   2
   1    75         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    77   0        4.30182E+00   4.48443E+00
   1    77   1        4.30185E+00   4.48453E+00
   1    77   2        4.30185E+00   4.48452E+00

   1    77         Fold Function:   6.92256E-01
   1    77         BP   Function:   5.34659E+01
   1    77         Hopf Function:   0.00000E+00

   1    77         Eigenvalues  :   Stable:   2
   1    77         Eigenvalue  1:  -1.47041E+00   0.00000E+00
   1    77         Eigenvalue  2:  -1.25855E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -77        0   4.30185E+00   4.48452E+00   4.30185E+00   1.26690E+00

   1    76         Iterations   :   2
   1    76         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    78   0        4.34337E+00   4.52093E+00
   1    78   1        4.34340E+00   4.52102E+00
   1    78   2        4.34340E+00   4.52102E+00

   1    78         Fold Function:   6.92799E-01
   1    78         BP   Function:   5.44610E+01
   1    78         Hopf Function:   0.00000E+00

   1    78         Eigenvalues  :   Stable:   2
   1    78         Eigenvalue  1:  -1.45571E+00   0.00000E+00
   1    78         Eigenvalue  2:  -1.29595E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -78        0   4.34340E+00   4.52102E+00   4.34340E+00   1.25478E+00

   1    77         Iterations   :   2
   1    77         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    79   0        4.38496E+00   4.55763E+00
   1    79   1        4.38499E+00   4.55773E+00
   1    79   2        4.38499E+00   4.55773E+00

   1    79         Fold Function:   6.93319E-01
   1    79         BP   Function:   5.54672E+01
   1    79         Hopf Function:   0.00000E+00

   1    79         Eigenvalues  :   Stable:   2
   1    79         Eigenvalue  1:  -1.44178E+00   0.00000E+00
   1    79         Eigenvalue  2:  -1.33363E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -79        0   4.38499E+00   4.55773E+00   4.38499E+00   1.24288E+00

   1    78         Iterations   :   2
   1    78         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    80   0        4.42657E+00   4.59455E+00
   1    80   1        4.42660E+00   4.59463E+00
   1    80   2        4.42660E+00   4.59463E+00

   1    80         Fold Function:   6.93816E-01
   1    80         BP   Function:   5.64845E+01
   1    80         Hopf Function:   0.00000E+00

   1    80         Eigenvalues  :   Stable:   2
   1    80         Eigenvalue  1:  -1.42859E+00   0.00000E+00
   1    80         Eigenvalue  2:  -1.37162E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -80        0   4.42660E+00   4.59463E+00   4.42660E+00   1.23119E+00

   1    79         Iterations   :   2
   1    79         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    81   0        4.46822E+00   4.63165E+00
   1    81   1        4.46825E+00   4.63173E+00
   1    81   2        4.46825E+00   4.63173E+00

   1    81         Fold Function:   6.94291E-01
   1    81         BP   Function:   5.75128E+01
   1    81         Hopf Function:   0.00000E+00

   1    81         Eigenvalues  :   Stable:   2
   1    81         Eigenvalue  1:  -1.41606E+00   0.00000E+00
   1    81         Eigenvalue  2:  -1.40992E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -81        0   4.46825E+00   4.63173E+00   4.46825E+00   1.21972E+00

   1    80         Iterations   :   2
   1    80         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    82   0        4.50989E+00   4.66893E+00
   1    82   1        4.50992E+00   4.66901E+00
   1    82   2        4.50992E+00   4.66901E+00

   1    82         Fold Function:   6.94746E-01
   1    82         BP   Function:   5.85522E+01
   1    82         Hopf Function:   0.00000E+00

   1    82         Eigenvalues  :   Stable:   2
   1    82         Eigenvalue  1:  -1.40415E+00   0.00000E+00
   1    82         Eigenvalue  2:  -1.44852E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -82        0   4.50992E+00   4.66901E+00   4.50992E+00   1.20845E+00

   1    81         Iterations   :   2
   1    81         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    83   0        4.55159E+00   4.70640E+00
   1    83   1        4.55162E+00   4.70648E+00
   1    83   2        4.55161E+00   4.70648E+00

   1    83         Fold Function:   6.95182E-01
   1    83         BP   Function:   5.96025E+01
   1    83         Hopf Function:   0.00000E+00

   1    83         Eigenvalues  :   Stable:   2
   1    83         Eigenvalue  1:  -1.39281E+00   0.00000E+00
   1    83         Eigenvalue  2:  -1.48744E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -83        0   4.55161E+00   4.70648E+00   4.55161E+00   1.19738E+00

   1    82         Iterations   :   2
   1    82         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    84   0        4.59331E+00   4.74403E+00
   1    84   1        4.59334E+00   4.74411E+00
   1    84   2        4.59334E+00   4.74411E+00

   1    84         Fold Function:   6.95599E-01
   1    84         BP   Function:   6.06638E+01
   1    84         Hopf Function:   0.00000E+00

   1    84         Eigenvalues  :   Stable:   2
   1    84         Eigenvalue  1:  -1.38201E+00   0.00000E+00
   1    84         Eigenvalue  2:  -1.52668E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -84        0   4.59334E+00   4.74411E+00   4.59334E+00   1.18650E+00

   1    83         Iterations   :   2
   1    83         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    85   0        4.63506E+00   4.78183E+00
   1    85   1        4.63509E+00   4.78190E+00
   1    85   2        4.63509E+00   4.78190E+00

   1    85         Fold Function:   6.95998E-01
   1    85         BP   Function:   6.17361E+01
   1    85         Hopf Function:   0.00000E+00

   1    85         Eigenvalues  :   Stable:   2
   1    85         Eigenvalue  1:  -1.37170E+00   0.00000E+00
   1    85         Eigenvalue  2:  -1.56623E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -85        0   4.63509E+00   4.78190E+00   4.63509E+00   1.17581E+00

   1    84         Iterations   :   2
   1    84         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    86   0        4.67683E+00   4.81978E+00
   1    86   1        4.67686E+00   4.81985E+00
   1    86   2        4.67686E+00   4.81985E+00

   1    86         Fold Function:   6.96381E-01
   1    86         BP   Function:   6.28193E+01
   1    86         Hopf Function:   0.00000E+00

   1    86         Eigenvalues  :   Stable:   2
   1    86         Eigenvalue  1:  -1.36186E+00   0.00000E+00
   1    86         Eigenvalue  2:  -1.60611E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -86        0   4.67686E+00   4.81985E+00   4.67686E+00   1.16531E+00

   1    85         Iterations   :   2
   1    85         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    87   0        4.71863E+00   4.85789E+00
   1    87   1        4.71865E+00   4.85795E+00
   1    87   2        4.71865E+00   4.85795E+00

   1    87         Fold Function:   6.96748E-01
   1    87         BP   Function:   6.39134E+01
   1    87         Hopf Function:   0.00000E+00

   1    87         Eigenvalues  :   Stable:   2
   1    87         Eigenvalue  1:  -1.35245E+00   0.00000E+00
   1    87         Eigenvalue  2:  -1.64632E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -87        0   4.71865E+00   4.85795E+00   4.71865E+00   1.15499E+00

   1    86         Iterations   :   2
   1    86         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    88   0        4.76045E+00   4.89613E+00
   1    88   1        4.76047E+00   4.89619E+00
   1    88   2        4.76047E+00   4.89619E+00

   1    88         Fold Function:   6.97099E-01
   1    88         BP   Function:   6.50184E+01
   1    88         Hopf Function:   0.00000E+00

   1    88         Eigenvalues  :   Stable:   2
   1    88         Eigenvalue  1:  -1.34345E+00   0.00000E+00
   1    88         Eigenvalue  2:  -1.68686E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -88        0   4.76047E+00   4.89619E+00   4.76047E+00   1.14485E+00

   1    87         Iterations   :   2
   1    87         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    89   0        4.80228E+00   4.93452E+00
   1    89   1        4.80230E+00   4.93458E+00
   1    89   2        4.80230E+00   4.93458E+00

   1    89         Fold Function:   6.97437E-01
   1    89         BP   Function:   6.61342E+01
   1    89         Hopf Function:   0.00000E+00

   1    89         Eigenvalues  :   Stable:   2
   1    89         Eigenvalue  1:  -1.33482E+00   0.00000E+00
   1    89         Eigenvalue  2:  -1.72773E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -89        0   4.80230E+00   4.93458E+00   4.80230E+00   1.13487E+00

   1    88         Iterations   :   2
   1    88         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    90   0        4.84414E+00   4.97304E+00
   1    90   1        4.84416E+00   4.97309E+00
   1    90   2        4.84416E+00   4.97309E+00

   1    90         Fold Function:   6.97760E-01
   1    90         BP   Function:   6.72608E+01
   1    90         Hopf Function:   0.00000E+00

   1    90         Eigenvalues  :   Stable:   2
   1    90         Eigenvalue  1:  -1.32656E+00   0.00000E+00
   1    90         Eigenvalue  2:  -1.76893E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -90        0   4.84416E+00   4.97309E+00   4.84416E+00   1.12507E+00

   1    89         Iterations   :   2
   1    89         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    91   0        4.88602E+00   5.01168E+00
   1    91   1        4.88603E+00   5.01174E+00
   1    91   2        4.88603E+00   5.01174E+00

   1    91         Fold Function:   6.98070E-01
   1    91         BP   Function:   6.83983E+01
   1    91         Hopf Function:   0.00000E+00

   1    91         Eigenvalues  :   Stable:   2
   1    91         Eigenvalue  1:  -1.31863E+00   0.00000E+00
   1    91         Eigenvalue  2:  -1.81047E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -91        0   4.88603E+00   5.01174E+00   4.88603E+00   1.11542E+00

   1    90         Iterations   :   2
   1    90         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    92   0        4.92791E+00   5.05045E+00
   1    92   1        4.92793E+00   5.05050E+00
   1    92   2        4.92793E+00   5.05050E+00

   1    92         Fold Function:   6.98368E-01
   1    92         BP   Function:   6.95465E+01
   1    92         Hopf Function:   0.00000E+00

   1    92         Eigenvalues  :   Stable:   2
   1    92         Eigenvalue  1:  -1.31101E+00   0.00000E+00
   1    92         Eigenvalue  2:  -1.85235E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -92        0   4.92793E+00   5.05050E+00   4.92793E+00   1.10594E+00

   1    91         Iterations   :   2
   1    91         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    93   0        4.96982E+00   5.08934E+00
   1    93   1        4.96984E+00   5.08939E+00
   1    93   2        4.96984E+00   5.08939E+00

   1    93         Fold Function:   6.98654E-01
   1    93         BP   Function:   7.07056E+01
   1    93         Hopf Function:   0.00000E+00

   1    93         Eigenvalues  :   Stable:   2
   1    93         Eigenvalue  1:  -1.30370E+00   0.00000E+00
   1    93         Eigenvalue  2:  -1.89456E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -93        0   4.96984E+00   5.08939E+00   4.96984E+00   1.09662E+00

   1    92         Iterations   :   2
   1    92         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    94   0        5.01175E+00   5.12834E+00
   1    94   1        5.01177E+00   5.12838E+00
   1    94   2        5.01177E+00   5.12838E+00

   1    94         Fold Function:   6.98928E-01
   1    94         BP   Function:   7.18754E+01
   1    94         Hopf Function:   0.00000E+00

   1    94         Eigenvalues  :   Stable:   2
   1    94         Eigenvalue  1:  -1.29666E+00   0.00000E+00
   1    94         Eigenvalue  2:  -1.93711E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -94        0   5.01177E+00   5.12838E+00   5.01177E+00   1.08744E+00

   1    93         Iterations   :   2
   1    93         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    95   0        5.05369E+00   5.16744E+00
   1    95   1        5.05371E+00   5.16749E+00
   1    95   2        5.05371E+00   5.16749E+00

   1    95         Fold Function:   6.99192E-01
   1    95         BP   Function:   7.30559E+01
   1    95         Hopf Function:   0.00000E+00

   1    95         Eigenvalues  :   Stable:   2
   1    95         Eigenvalue  1:  -1.28989E+00   0.00000E+00
   1    95         Eigenvalue  2:  -1.98001E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -95        0   5.05371E+00   5.16749E+00   5.05371E+00   1.07842E+00

   1    94         Iterations   :   2
   1    94         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    96   0        5.09565E+00   5.20666E+00
   1    96   1        5.09567E+00   5.20670E+00
   1    96   2        5.09567E+00   5.20670E+00

   1    96         Fold Function:   6.99445E-01
   1    96         BP   Function:   7.42471E+01
   1    96         Hopf Function:   0.00000E+00

   1    96         Eigenvalues  :   Stable:   2
   1    96         Eigenvalue  1:  -1.28337E+00   0.00000E+00
   1    96         Eigenvalue  2:  -2.02325E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -96        0   5.09567E+00   5.20670E+00   5.09567E+00   1.06954E+00

   1    95         Iterations   :   2
   1    95         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    97   0        5.13763E+00   5.24597E+00
   1    97   1        5.13764E+00   5.24601E+00
   1    97   2        5.13764E+00   5.24601E+00

   1    97         Fold Function:   6.99689E-01
   1    97         BP   Function:   7.54491E+01
   1    97         Hopf Function:   0.00000E+00

   1    97         Eigenvalues  :   Stable:   2
   1    97         Eigenvalue  1:  -1.27710E+00   0.00000E+00
   1    97         Eigenvalue  2:  -2.06683E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -97        0   5.13764E+00   5.24601E+00   5.13764E+00   1.06080E+00

   1    96         Iterations   :   2
   1    96         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    98   0        5.17962E+00   5.28538E+00
   1    98   1        5.17963E+00   5.28542E+00
   1    98   2        5.17963E+00   5.28542E+00

   1    98         Fold Function:   6.99923E-01
   1    98         BP   Function:   7.66617E+01
   1    98         Hopf Function:   0.00000E+00

   1    98         Eigenvalues  :   Stable:   2
   1    98         Eigenvalue  1:  -1.27104E+00   0.00000E+00
   1    98         Eigenvalue  2:  -2.11075E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -98        0   5.17963E+00   5.28542E+00   5.17963E+00   1.05220E+00

   1    97         Iterations   :   2
   1    97         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    99   0        5.22162E+00   5.32489E+00
   1    99   1        5.22163E+00   5.32493E+00
   1    99   2        5.22163E+00   5.32493E+00

   1    99         Fold Function:   7.00148E-01
   1    99         BP   Function:   7.78850E+01
   1    99         Hopf Function:   0.00000E+00

   1    99         Eigenvalues  :   Stable:   2
   1    99         Eigenvalue  1:  -1.26520E+00   0.00000E+00
   1    99         Eigenvalue  2:  -2.15503E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1   -99        0   5.22163E+00   5.32493E+00   5.22163E+00   1.04373E+00

   1    98         Iterations   :   2
   1    98         Next Step    :   6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1   100   0        5.26364E+00   5.36448E+00
   1   100   1        5.26365E+00   5.36452E+00
   1   100   2        5.26365E+00   5.36452E+00

   1   100         Fold Function:   7.00364E-01
   1   100         BP   Function:   7.91190E+01
   1   100         Hopf Function:   0.00000E+00

   1   100         Eigenvalues  :   Stable:   2
   1   100         Eigenvalue  1:  -1.25957E+00   0.00000E+00
   1   100         Eigenvalue  2:  -2.19964E+01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     1         Hopf Function:   2.25000E-01

   1     1         Eigenvalues  :   Stable:   0
   1     1         Eigenvalue  1:   2.25000E-01  -1.98730E+00
   1     1         Eigenvalue  2:   2.25000E-01   1.98730E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     1  EP    1   2.00000E+00   3.38018E+00   2.00000E+00   2.72500E+00
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     2   0        1.98982E+00   3.38538E+00
   1     2   1        1.98984E+00   3.38543E+00
   1     2   2        1.98984E+00   3.38543E+00

===============================================

  BR    PT  IT         PAR           L2-NORM
   1     2   0        1.97968E+00   3.39075E+00
   1     2   1        1.97973E+00   3.39084E+00
   1     2   2        1.97973E+00   3.39084E+00

   1     2         Fold Function:   5.04202E-01
   1     2         BP   Function:   1.55468E+01
   1     2         Hopf Function:   2.65332E-01

   1     2         Eigenvalues  :   Stable:   0
   1     2         Eigenvalue  1:   2.65332E-01  -1.96187E+00
   1     2         Eigenvalue  2:   2.65332E-01   1.96187E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     2        0   1.97973E+00   3.39084E+00   1.97973E+00   2.75290E+00

   1     1         Iterations   :   2
   1     1         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     3   0        1.96457E+00   3.39911E+00
   1     3   1        1.96466E+00   3.39927E+00
   1     3   2        1.96466E+00   3.39927E+00
   1     3   3        1.96466E+00   3.39927E+00

   1     3         Fold Function:   5.00399E-01
   1     3         BP   Function:   1.54272E+01
   1     3         Hopf Function:   2.95051E-01

   1     3         Eigenvalues  :   Stable:   0
   1     3         Eigenvalue  1:   2.95051E-01  -1.94238E+00
   1     3         Eigenvalue  2:   2.95051E-01   1.94238E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     3        0   1.96466E+00   3.39927E+00   1.96466E+00   2.77401E+00

   1     2         Iterations   :   3
   1     2         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     4   0        1.94959E+00   3.40788E+00
   1     4   1        1.94971E+00   3.40808E+00
   1     4   2        1.94971E+00   3.40808E+00
   1     4   3        1.94971E+00   3.40808E+00

   1     4         Fold Function:   4.96568E-01
   1     4         BP   Function:   1.53104E+01
   1     4         Hopf Function:   3.24320E-01

   1     4         Eigenvalues  :   Stable:   0
   1     4         Eigenvalue  1:   3.24320E-01  -1.92254E+00
   1     4         Eigenvalue  2:   3.24320E-01   1.92254E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     4        0   1.94971E+00   3.40808E+00   1.94971E+00   2.79529E+00

   1     3         Iterations   :   3
   1     3         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     5   0        1.93475E+00   3.41706E+00
   1     5   1        1.93487E+00   3.41726E+00
   1     5   2        1.93487E+00   3.41726E+00
   1     5   3        1.93487E+00   3.41726E+00

   1     5         Fold Function:   4.92708E-01
   1     5         BP   Function:   1.51964E+01
   1     5         Hopf Function:   3.53142E-01

   1     5         Eigenvalues  :   Stable:   0
   1     5         Eigenvalue  1:   3.53142E-01  -1.90237E+00
   1     5         Eigenvalue  2:   3.53142E-01   1.90237E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     5        0   1.93487E+00   3.41726E+00   1.93487E+00   2.81673E+00

   1     4         Iterations   :   3
   1     4         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     6   0        1.92003E+00   3.42662E+00
   1     6   1        1.92014E+00   3.42681E+00
   1     6   2        1.92015E+00   3.42681E+00
   1     6   3        1.92015E+00   3.42681E+00

   1     6         Fold Function:   4.88822E-01
   1     6         BP   Function:   1.50850E+01
   1     6         Hopf Function:   3.81521E-01

   1     6         Eigenvalues  :   Stable:   0
   1     6         Eigenvalue  1:   3.81521E-01  -1.88186E+00
   1     6         Eigenvalue  2:   3.81521E-01   1.88186E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     6        0   1.92015E+00   3.42681E+00   1.92015E+00   2.83833E+00

   1     5         Iterations   :   3
   1     5         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     7   0        1.90542E+00   3.43654E+00
   1     7   1        1.90554E+00   3.43674E+00
   1     7   2        1.90554E+00   3.43674E+00
   1     7   3        1.90554E+00   3.43674E+00

   1     7         Fold Function:   4.84912E-01
   1     7         BP   Function:   1.49761E+01
   1     7         Hopf Function:   4.09460E-01

   1     7         Eigenvalues  :   Stable:   0
   1     7         Eigenvalue  1:   4.09460E-01  -1.86103E+00
   1     7         Eigenvalue  2:   4.09460E-01   1.86103E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     7        0   1.90554E+00   3.43674E+00   1.90554E+00   2.86008E+00

   1     6         Iterations   :   3
   1     6         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     8   0        1.89093E+00   3.44683E+00
   1     8   1        1.89105E+00   3.44702E+00
   1     8   2        1.89105E+00   3.44702E+00
   1     8   3        1.89105E+00   3.44702E+00

   1     8         Fold Function:   4.80979E-01
   1     8         BP   Function:   1.48699E+01
   1     8         Hopf Function:   4.36964E-01

   1     8         Eigenvalues  :   Stable:   0
   1     8         Eigenvalue  1:   4.36964E-01  -1.83987E+00
   1     8         Eigenvalue  2:   4.36964E-01   1.83987E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     8        0   1.89105E+00   3.44702E+00   1.89105E+00   2.88200E+00

   1     7         Iterations   :   3
   1     7         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1     9   0        1.87656E+00   3.45748E+00
   1     9   1        1.87668E+00   3.45768E+00
   1     9   2        1.87668E+00   3.45767E+00
   1     9   3        1.87668E+00   3.45767E+00

   1     9         Fold Function:   4.77025E-01
   1     9         BP   Function:   1.47661E+01
   1     9         Hopf Function:   4.64035E-01

   1     9         Eigenvalues  :   Stable:   0
   1     9         Eigenvalue  1:   4.64035E-01  -1.81841E+00
   1     9         Eigenvalue  2:   4.64035E-01   1.81841E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1     9        0   1.87668E+00   3.45767E+00   1.87668E+00   2.90406E+00

   1     8         Iterations   :   3
   1     8         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    10   0        1.86231E+00   3.46849E+00
   1    10   1        1.86243E+00   3.46869E+00
   1    10   2        1.86243E+00   3.46869E+00
   1    10   3        1.86243E+00   3.46869E+00

   1    10         Fold Function:   4.73051E-01
   1    10         BP   Function:   1.46649E+01
   1    10         Hopf Function:   4.90678E-01

   1    10         Eigenvalues  :   Stable:   0
   1    10         Eigenvalue  1:   4.90678E-01  -1.79663E+00
   1    10         Eigenvalue  2:   4.90678E-01   1.79663E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    10        0   1.86243E+00   3.46869E+00   1.86243E+00   2.92629E+00

   1     9         Iterations   :   3
   1     9         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    11   0        1.84818E+00   3.47986E+00
   1    11   1        1.84830E+00   3.48006E+00
   1    11   2        1.84830E+00   3.48006E+00
   1    11   3        1.84830E+00   3.48006E+00

   1    11         Fold Function:   4.69060E-01
   1    11         BP   Function:   1.45661E+01
   1    11         Hopf Function:   5.16898E-01

   1    11         Eigenvalues  :   Stable:   0
   1    11         Eigenvalue  1:   5.16898E-01  -1.77455E+00
   1    11         Eigenvalue  2:   5.16898E-01   1.77455E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    11        0   1.84830E+00   3.48006E+00   1.84830E+00   2.94866E+00

   1    10         Iterations   :   3
   1    10         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    12   0        1.83417E+00   3.49159E+00
   1    12   1        1.83429E+00   3.49178E+00
   1    12   2        1.83429E+00   3.49178E+00
   1    12   3        1.83429E+00   3.49178E+00

   1    12         Fold Function:   4.65053E-01
   1    12         BP   Function:   1.44697E+01
   1    12         Hopf Function:   5.42698E-01

   1    12         Eigenvalues  :   Stable:   0
   1    12         Eigenvalue  1:   5.42698E-01  -1.75217E+00
   1    12         Eigenvalue  2:   5.42698E-01   1.75217E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    12        0   1.83429E+00   3.49178E+00   1.83429E+00   2.97118E+00

   1    11         Iterations   :   3
   1    11         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    13   0        1.82027E+00   3.50367E+00
   1    13   1        1.82039E+00   3.50386E+00
   1    13   2        1.82039E+00   3.50386E+00
   1    13   3        1.82039E+00   3.50386E+00

   1    13         Fold Function:   4.61032E-01
   1    13         BP   Function:   1.43756E+01
   1    13         Hopf Function:   5.68082E-01

   1    13         Eigenvalues  :   Stable:   0
   1    13         Eigenvalue  1:   5.68082E-01  -1.72949E+00
   1    13         Eigenvalue  2:   5.68082E-01   1.72949E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    13        0   1.82039E+00   3.50386E+00   1.82039E+00   2.99386E+00

   1    12         Iterations   :   3
   1    12         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    14   0        1.80650E+00   3.51609E+00
   1    14   1        1.80662E+00   3.51628E+00
   1    14   2        1.80662E+00   3.51628E+00
   1    14   3        1.80662E+00   3.51628E+00

   1    14         Fold Function:   4.56998E-01
   1    14         BP   Function:   1.42839E+01
   1    14         Hopf Function:   5.93055E-01

   1    14         Eigenvalues  :   Stable:   0
   1    14         Eigenvalue  1:   5.93055E-01  -1.70651E+00
   1    14         Eigenvalue  2:   5.93055E-01   1.70651E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    14        0   1.80662E+00   3.51628E+00   1.80662E+00   3.01668E+00

   1    13         Iterations   :   3
   1    13         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    15   0        1.79285E+00   3.52886E+00
   1    15   1        1.79297E+00   3.52905E+00
   1    15   2        1.79297E+00   3.52905E+00
   1    15   3        1.79297E+00   3.52905E+00

   1    15         Fold Function:   4.52954E-01
   1    15         BP   Function:   1.41945E+01
   1    15         Hopf Function:   6.17621E-01

   1    15         Eigenvalues  :   Stable:   0
   1    15         Eigenvalue  1:   6.17621E-01  -1.68324E+00
   1    15         Eigenvalue  2:   6.17621E-01   1.68324E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    15        0   1.79297E+00   3.52905E+00   1.79297E+00   3.03964E+00

   1    14         Iterations   :   3
   1    14         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    16   0        1.77933E+00   3.54197E+00
   1    16   1        1.77945E+00   3.54216E+00
   1    16   2        1.77945E+00   3.54216E+00
   1    16   3        1.77945E+00   3.54216E+00

   1    16         Fold Function:   4.48902E-01
   1    16         BP   Function:   1.41074E+01
   1    16         Hopf Function:   6.41785E-01

   1    16         Eigenvalues  :   Stable:   0
   1    16         Eigenvalue  1:   6.41785E-01  -1.65968E+00
   1    16         Eigenvalue  2:   6.41785E-01   1.65968E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    16        0   1.77945E+00   3.54216E+00   1.77945E+00   3.06275E+00

   1    15         Iterations   :   3
   1    15         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    17   0        1.76592E+00   3.55542E+00
   1    17   1        1.76604E+00   3.55560E+00
   1    17   2        1.76604E+00   3.55560E+00
   1    17   3        1.76604E+00   3.55560E+00

   1    17         Fold Function:   4.44842E-01
   1    17         BP   Function:   1.40224E+01
   1    17         Hopf Function:   6.65550E-01

   1    17         Eigenvalues  :   Stable:   0
   1    17         Eigenvalue  1:   6.65550E-01  -1.63583E+00
   1    17         Eigenvalue  2:   6.65550E-01   1.63583E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    17        0   1.76604E+00   3.55560E+00   1.76604E+00   3.08600E+00

   1    16         Iterations   :   3
   1    16         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    18   0        1.75263E+00   3.56920E+00
   1    18   1        1.75276E+00   3.56938E+00
   1    18   2        1.75276E+00   3.56938E+00
   1    18   3        1.75276E+00   3.56938E+00

   1    18         Fold Function:   4.40778E-01
   1    18         BP   Function:   1.39396E+01
   1    18         Hopf Function:   6.88923E-01

   1    18         Eigenvalues  :   Stable:   0
   1    18         Eigenvalue  1:   6.88923E-01  -1.61169E+00
   1    18         Eigenvalue  2:   6.88923E-01   1.61169E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    18        0   1.75276E+00   3.56938E+00   1.75276E+00   3.10939E+00

   1    17         Iterations   :   3
   1    17         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    19   0        1.73947E+00   3.58330E+00
   1    19   1        1.73959E+00   3.58348E+00
   1    19   2        1.73959E+00   3.58348E+00
   1    19   3        1.73959E+00   3.58348E+00

   1    19         Fold Function:   4.36710E-01
   1    19         BP   Function:   1.38589E+01
   1    19         Hopf Function:   7.11907E-01

   1    19         Eigenvalues  :   Stable:   0
   1    19         Eigenvalue  1:   7.11907E-01  -1.58725E+00
   1    19         Eigenvalue  2:   7.11907E-01   1.58725E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    19        0   1.73959E+00   3.58348E+00   1.73959E+00   3.13292E+00

   1    18         Iterations   :   3
   1    18         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    20   0        1.72643E+00   3.59773E+00
   1    20   1        1.72655E+00   3.59791E+00
   1    20   2        1.72655E+00   3.59791E+00
   1    20   3        1.72655E+00   3.59791E+00

   1    20         Fold Function:   4.32641E-01
   1    20         BP   Function:   1.37803E+01
   1    20         Hopf Function:   7.34506E-01

   1    20         Eigenvalues  :   Stable:   0
   1    20         Eigenvalue  1:   7.34506E-01  -1.56253E+00
   1    20         Eigenvalue  2:   7.34506E-01   1.56253E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    20        0   1.72655E+00   3.59791E+00   1.72655E+00   3.15658E+00

   1    19         Iterations   :   3
   1    19         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    21   0        1.71351E+00   3.61249E+00
   1    21   1        1.71364E+00   3.61266E+00
   1    21   2        1.71364E+00   3.61266E+00
   1    21   3        1.71364E+00   3.61266E+00

   1    21         Fold Function:   4.28571E-01
   1    21         BP   Function:   1.37038E+01
   1    21         Hopf Function:   7.56727E-01

   1    21         Eigenvalues  :   Stable:   0
   1    21         Eigenvalue  1:   7.56727E-01  -1.53750E+00
   1    21         Eigenvalue  2:   7.56727E-01   1.53750E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    21        0   1.71364E+00   3.61266E+00   1.71364E+00   3.18037E+00

   1    20         Iterations   :   3
   1    20         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    22   0        1.70072E+00   3.62755E+00
   1    22   1        1.70084E+00   3.62773E+00
   1    22   2        1.70084E+00   3.62773E+00
   1    22   3        1.70084E+00   3.62773E+00

   1    22         Fold Function:   4.24504E-01
   1    22         BP   Function:   1.36292E+01
   1    22         Hopf Function:   7.78573E-01

   1    22         Eigenvalues  :   Stable:   0
   1    22         Eigenvalue  1:   7.78573E-01  -1.51218E+00
   1    22         Eigenvalue  2:   7.78573E-01   1.51218E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    22        0   1.70084E+00   3.62773E+00   1.70084E+00   3.20430E+00

   1    21         Iterations   :   3
   1    21         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    23   0        1.68804E+00   3.64293E+00
   1    23   1        1.68816E+00   3.64310E+00
   1    23   2        1.68817E+00   3.64310E+00
   1    23   3        1.68817E+00   3.64310E+00

   1    23         Fold Function:   4.20440E-01
   1    23         BP   Function:   1.35567E+01
   1    23         Hopf Function:   8.00049E-01

   1    23         Eigenvalues  :   Stable:   0
   1    23         Eigenvalue  1:   8.00049E-01  -1.48655E+00
   1    23         Eigenvalue  2:   8.00049E-01   1.48655E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    23        0   1.68817E+00   3.64310E+00   1.68817E+00   3.22836E+00

   1    22         Iterations   :   3
   1    22         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    24   0        1.67549E+00   3.65862E+00
   1    24   1        1.67561E+00   3.65878E+00
   1    24   2        1.67561E+00   3.65878E+00
   1    24   3        1.67561E+00   3.65878E+00

   1    24         Fold Function:   4.16382E-01
   1    24         BP   Function:   1.34860E+01
   1    24         Hopf Function:   8.21161E-01

   1    24         Eigenvalues  :   Stable:   0
   1    24         Eigenvalue  1:   8.21161E-01  -1.46061E+00
   1    24         Eigenvalue  2:   8.21161E-01   1.46061E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    24        0   1.67561E+00   3.65878E+00   1.67561E+00   3.25254E+00

   1    23         Iterations   :   3
   1    23         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    25   0        1.66306E+00   3.67460E+00
   1    25   1        1.66318E+00   3.67477E+00
   1    25   2        1.66318E+00   3.67477E+00
   1    25   3        1.66318E+00   3.67477E+00

   1    25         Fold Function:   4.12330E-01
   1    25         BP   Function:   1.34172E+01
   1    25         Hopf Function:   8.41913E-01

   1    25         Eigenvalues  :   Stable:   0
   1    25         Eigenvalue  1:   8.41913E-01  -1.43435E+00
   1    25         Eigenvalue  2:   8.41913E-01   1.43435E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    25        0   1.66318E+00   3.67477E+00   1.66318E+00   3.27685E+00

   1    24         Iterations   :   3
   1    24         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    26   0        1.65075E+00   3.69089E+00
   1    26   1        1.65087E+00   3.69105E+00
   1    26   2        1.65087E+00   3.69105E+00
   1    26   3        1.65087E+00   3.69105E+00

   1    26         Fold Function:   4.08286E-01
   1    26         BP   Function:   1.33503E+01
   1    26         Hopf Function:   8.62309E-01

   1    26         Eigenvalues  :   Stable:   0
   1    26         Eigenvalue  1:   8.62309E-01  -1.40777E+00
   1    26         Eigenvalue  2:   8.62309E-01   1.40777E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    26        0   1.65087E+00   3.69105E+00   1.65087E+00   3.30128E+00

   1    25         Iterations   :   3
   1    25         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    27   0        1.63856E+00   3.70746E+00
   1    27   1        1.63868E+00   3.70763E+00
   1    27   2        1.63868E+00   3.70763E+00
   1    27   3        1.63868E+00   3.70763E+00

   1    27         Fold Function:   4.04253E-01
   1    27         BP   Function:   1.32851E+01
   1    27         Hopf Function:   8.82356E-01

   1    27         Eigenvalues  :   Stable:   0
   1    27         Eigenvalue  1:   8.82356E-01  -1.38085E+00
   1    27         Eigenvalue  2:   8.82356E-01   1.38085E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    27        0   1.63868E+00   3.70763E+00   1.63868E+00   3.32584E+00

   1    26         Iterations   :   3
   1    26         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    28   0        1.62650E+00   3.72433E+00
   1    28   1        1.62662E+00   3.72449E+00
   1    28   2        1.62662E+00   3.72449E+00
   1    28   3        1.62662E+00   3.72449E+00

   1    28         Fold Function:   4.00231E-01
   1    28         BP   Function:   1.32217E+01
   1    28         Hopf Function:   9.02058E-01

   1    28         Eigenvalues  :   Stable:   0
   1    28         Eigenvalue  1:   9.02058E-01  -1.35358E+00
   1    28         Eigenvalue  2:   9.02058E-01   1.35358E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    28        0   1.62662E+00   3.72449E+00   1.62662E+00   3.35051E+00

   1    27         Iterations   :   3
   1    27         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    29   0        1.61455E+00   3.74148E+00
   1    29   1        1.61467E+00   3.74163E+00
   1    29   2        1.61467E+00   3.74163E+00
   1    29   3        1.61467E+00   3.74163E+00

   1    29         Fold Function:   3.96222E-01
   1    29         BP   Function:   1.31600E+01
   1    29         Hopf Function:   9.21419E-01

   1    29         Eigenvalues  :   Stable:   0
   1    29         Eigenvalue  1:   9.21419E-01  -1.32595E+00
   1    29         Eigenvalue  2:   9.21419E-01   1.32595E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    29        0   1.61467E+00   3.74163E+00   1.61467E+00   3.37530E+00

   1    28         Iterations   :   3
   1    28         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    30   0        1.60272E+00   3.75890E+00
   1    30   1        1.60284E+00   3.75906E+00
   1    30   2        1.60284E+00   3.75906E+00
   1    30   3        1.60284E+00   3.75906E+00

   1    30         Fold Function:   3.92227E-01
   1    30         BP   Function:   1.31000E+01
   1    30         Hopf Function:   9.40446E-01

   1    30         Eigenvalues  :   Stable:   0
   1    30         Eigenvalue  1:   9.40446E-01  -1.29795E+00
   1    30         Eigenvalue  2:   9.40446E-01   1.29795E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    30        0   1.60284E+00   3.75906E+00   1.60284E+00   3.40021E+00

   1    29         Iterations   :   3
   1    29         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    31   0        1.59102E+00   3.77660E+00
   1    31   1        1.59114E+00   3.77676E+00
   1    31   2        1.59114E+00   3.77675E+00
   1    31   3        1.59114E+00   3.77675E+00

   1    31         Fold Function:   3.88249E-01
   1    31         BP   Function:   1.30417E+01
   1    31         Hopf Function:   9.59142E-01

   1    31         Eigenvalues  :   Stable:   0
   1    31         Eigenvalue  1:   9.59142E-01  -1.26955E+00
   1    31         Eigenvalue  2:   9.59142E-01   1.26955E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    31        0   1.59114E+00   3.77675E+00   1.59114E+00   3.42522E+00

   1    30         Iterations   :   3
   1    30         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    32   0        1.57943E+00   3.79457E+00
   1    32   1        1.57955E+00   3.79472E+00
   1    32   2        1.57955E+00   3.79472E+00
   1    32   3        1.57955E+00   3.79472E+00

   1    32         Fold Function:   3.84287E-01
   1    32         BP   Function:   1.29849E+01
   1    32         Hopf Function:   9.77513E-01

   1    32         Eigenvalues  :   Stable:   0
   1    32         Eigenvalue  1:   9.77513E-01  -1.24074E+00
   1    32         Eigenvalue  2:   9.77513E-01   1.24074E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    32        0   1.57955E+00   3.79472E+00   1.57955E+00   3.45035E+00

   1    31         Iterations   :   3
   1    31         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    33   0        1.56796E+00   3.81280E+00
   1    33   1        1.56808E+00   3.81295E+00
   1    33   2        1.56808E+00   3.81295E+00
   1    33   3        1.56808E+00   3.81295E+00

   1    33         Fold Function:   3.80343E-01
   1    33         BP   Function:   1.29297E+01
   1    33         Hopf Function:   9.95564E-01

   1    33         Eigenvalues  :   Stable:   0
   1    33         Eigenvalue  1:   9.95564E-01  -1.21150E+00
   1    33         Eigenvalue  2:   9.95564E-01   1.21150E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    33        0   1.56808E+00   3.81295E+00   1.56808E+00   3.47559E+00

   1    32         Iterations   :   3
   1    32         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    34   0        1.55661E+00   3.83129E+00
   1    34   1        1.55673E+00   3.83144E+00
   1    34   2        1.55673E+00   3.83144E+00
   1    34   3        1.55673E+00   3.83144E+00

   1    34         Fold Function:   3.76420E-01
   1    34         BP   Function:   1.28760E+01
   1    34         Hopf Function:   1.01330E+00

   1    34         Eigenvalues  :   Stable:   0
   1    34         Eigenvalue  1:   1.01330E+00  -1.18179E+00
   1    34         Eigenvalue  2:   1.01330E+00   1.18179E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    34        0   1.55673E+00   3.83144E+00   1.55673E+00   3.50093E+00

   1    33         Iterations   :   3
   1    33         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    35   0        1.54538E+00   3.85004E+00
   1    35   1        1.54549E+00   3.85018E+00
   1    35   2        1.54549E+00   3.85018E+00
   1    35   3        1.54549E+00   3.85018E+00

   1    35         Fold Function:   3.72517E-01
   1    35         BP   Function:   1.28238E+01
   1    35         Hopf Function:   1.03072E+00

   1    35         Eigenvalues  :   Stable:   0
   1    35         Eigenvalue  1:   1.03072E+00  -1.15159E+00
   1    35         Eigenvalue  2:   1.03072E+00   1.15159E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    35        0   1.54549E+00   3.85018E+00   1.54549E+00   3.52638E+00

   1    34         Iterations   :   3
   1    34         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    36   0        1.53426E+00   3.86904E+00
   1    36   1        1.53438E+00   3.86918E+00
   1    36   2        1.53438E+00   3.86918E+00
   1    36   3        1.53438E+00   3.86918E+00

   1    36         Fold Function:   3.68636E-01
   1    36         BP   Function:   1.27730E+01
   1    36         Hopf Function:   1.04784E+00

   1    36         Eigenvalues  :   Stable:   0
   1    36         Eigenvalue  1:   1.04784E+00  -1.12086E+00
   1    36         Eigenvalue  2:   1.04784E+00   1.12086E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    36        0   1.53438E+00   3.86918E+00   1.53438E+00   3.55193E+00

   1    35         Iterations   :   3
   1    35         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    37   0        1.52326E+00   3.88828E+00
   1    37   1        1.52338E+00   3.88841E+00
   1    37   2        1.52338E+00   3.88841E+00
   1    37   3        1.52338E+00   3.88841E+00

   1    37         Fold Function:   3.64778E-01
   1    37         BP   Function:   1.27237E+01
   1    37         Hopf Function:   1.06466E+00

   1    37         Eigenvalues  :   Stable:   0
   1    37         Eigenvalue  1:   1.06466E+00  -1.08957E+00
   1    37         Eigenvalue  2:   1.06466E+00   1.08957E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    37        0   1.52338E+00   3.88841E+00   1.52338E+00   3.57758E+00

   1    36         Iterations   :   3
   1    36         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    38   0        1.51237E+00   3.90776E+00
   1    38   1        1.51249E+00   3.90789E+00
   1    38   2        1.51249E+00   3.90789E+00
   1    38   3        1.51249E+00   3.90789E+00

   1    38         Fold Function:   3.60944E-01
   1    38         BP   Function:   1.26757E+01
   1    38         Hopf Function:   1.08119E+00

   1    38         Eigenvalues  :   Stable:   0
   1    38         Eigenvalue  1:   1.08119E+00  -1.05767E+00
   1    38         Eigenvalue  2:   1.08119E+00   1.05767E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    38        0   1.51249E+00   3.90789E+00   1.51249E+00   3.60333E+00

   1    37         Iterations   :   3
   1    37         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    39   0        1.50160E+00   3.92747E+00
   1    39   1        1.50172E+00   3.92760E+00
   1    39   2        1.50172E+00   3.92760E+00
   1    39   3        1.50172E+00   3.92760E+00

   1    39         Fold Function:   3.57135E-01
   1    39         BP   Function:   1.26291E+01
   1    39         Hopf Function:   1.09742E+00

   1    39         Eigenvalues  :   Stable:   0
   1    39         Eigenvalue  1:   1.09742E+00  -1.02510E+00
   1    39         Eigenvalue  2:   1.09742E+00   1.02510E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    39        0   1.50172E+00   3.92760E+00   1.50172E+00   3.62918E+00

   1    38         Iterations   :   3
   1    38         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    40   0        1.49095E+00   3.94742E+00
   1    40   1        1.49106E+00   3.94755E+00
   1    40   2        1.49106E+00   3.94755E+00
   1    40   3        1.49106E+00   3.94755E+00

   1    40         Fold Function:   3.53352E-01
   1    40         BP   Function:   1.25838E+01
   1    40         Hopf Function:   1.11337E+00

   1    40         Eigenvalues  :   Stable:   0
   1    40         Eigenvalue  1:   1.11337E+00  -9.91804E-01
   1    40         Eigenvalue  2:   1.11337E+00   9.91804E-01

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    40        0   1.49106E+00   3.94755E+00   1.49106E+00   3.65511E+00

   1    39         Iterations   :   3
   1    39         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    41   0        1.48040E+00   3.96759E+00
   1    41   1        1.48052E+00   3.96772E+00
   1    41   2        1.48052E+00   3.96772E+00
   1    41   3        1.48052E+00   3.96772E+00

   1    41         Fold Function:   3.49596E-01
   1    41         BP   Function:   1.25397E+01
   1    41         Hopf Function:   1.12903E+00

   1    41         Eigenvalues  :   Stable:   0
   1    41         Eigenvalue  1:   1.12903E+00  -9.57712E-01
   1    41         Eigenvalue  2:   1.12903E+00   9.57712E-01

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    41        0   1.48052E+00   3.96772E+00   1.48052E+00   3.68115E+00

   1    40         Iterations   :   3
   1    40         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    42   0        1.46997E+00   3.98798E+00
   1    42   1        1.47009E+00   3.98811E+00
   1    42   2        1.47009E+00   3.98811E+00
   1    42   3        1.47009E+00   3.98811E+00

   1    42         Fold Function:   3.45868E-01
   1    42         BP   Function:   1.24969E+01
   1    42         Hopf Function:   1.14442E+00

   1    42         Eigenvalues  :   Stable:   0
   1    42         Eigenvalue  1:   1.14442E+00  -9.22737E-01
   1    42         Eigenvalue  2:   1.14442E+00   9.22737E-01

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    42        0   1.47009E+00   3.98811E+00   1.47009E+00   3.70727E+00

   1    41         Iterations   :   3
   1    41         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    43   0        1.45965E+00   4.00859E+00
   1    43   1        1.45976E+00   4.00871E+00
   1    43   2        1.45976E+00   4.00871E+00
   1    43   3        1.45976E+00   4.00871E+00

   1    43         Fold Function:   3.42168E-01
   1    43         BP   Function:   1.24553E+01
   1    43         Hopf Function:   1.15954E+00

   1    43         Eigenvalues  :   Stable:   0
   1    43         Eigenvalue  1:   1.15954E+00  -8.86776E-01
   1    43         Eigenvalue  2:   1.15954E+00   8.86776E-01

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    43        0   1.45976E+00   4.00871E+00   1.45976E+00   3.73348E+00

   1    42         Iterations   :   3
   1    42         Next Step    :  -3.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    44   0        1.44944E+00   4.02941E+00
   1    44   1        1.44955E+00   4.02953E+00
   1    44   2        1.44955E+00   4.02953E+00

   1    44         Fold Function:   3.38497E-01
   1    44         BP   Function:   1.24151E+01
   1    44         Hopf Function:   1.17440E+00

   1    44         Eigenvalues  :   Stable:   0
   1    44         Eigenvalue  1:   1.17440E+00  -8.49709E-01
   1    44         Eigenvalue  2:   1.17440E+00   8.49709E-01

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    44        0   1.44955E+00   4.02953E+00   1.44955E+00   3.75977E+00

   1    43         Iterations   :   2
   1    43         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    45   0        1.43424E+00   4.06093E+00
   1    45   1        1.43444E+00   4.06115E+00
   1    45   2        1.43445E+00   4.06115E+00
   1    45   3        1.43445E+00   4.06115E+00

   1    45         Fold Function:   3.33047E-01
   1    45         BP   Function:   1.23563E+01
   1    45         Hopf Function:   1.19618E+00

   1    45         Eigenvalues  :   Stable:   0
   1    45         Eigenvalue  1:   1.19618E+00  -7.91694E-01
   1    45         Eigenvalue  2:   1.19618E+00   7.91694E-01

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    45        0   1.43445E+00   4.06115E+00   1.43445E+00   3.79938E+00

   1    44         Iterations   :   3
   1    44         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    46   0        1.41934E+00   4.09296E+00
   1    46   1        1.41958E+00   4.09321E+00
   1    46   2        1.41958E+00   4.09321E+00
   1    46   3        1.41958E+00   4.09321E+00

   1    46         Fold Function:   3.27667E-01
   1    46         BP   Function:   1.23002E+01
   1    46         Hopf Function:   1.21740E+00

   1    46         Eigenvalues  :   Stable:   0
   1    46         Eigenvalue  1:   1.21740E+00  -7.30172E-01
   1    46         Eigenvalue  2:   1.21740E+00   7.30172E-01

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    46        0   1.41958E+00   4.09321E+00   1.41958E+00   3.83916E+00

   1    45         Iterations   :   3
   1    45         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    47   0        1.40471E+00   4.12547E+00
   1    47   1        1.40495E+00   4.12572E+00
   1    47   2        1.40495E+00   4.12572E+00
   1    47   3        1.40495E+00   4.12572E+00

   1    47         Fold Function:   3.22357E-01
   1    47         BP   Function:   1.22465E+01
   1    47         Hopf Function:   1.23805E+00

   1    47         Eigenvalues  :   Stable:   0
   1    47         Eigenvalue  1:   1.23805E+00  -6.64172E-01
   1    47         Eigenvalue  2:   1.23805E+00   6.64172E-01

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    47        0   1.40495E+00   4.12572E+00   1.40495E+00   3.87913E+00

   1    46         Iterations   :   3
   1    46         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    48   0        1.39033E+00   4.15840E+00
   1    48   1        1.39057E+00   4.15865E+00
   1    48   2        1.39057E+00   4.15864E+00
   1    48   3        1.39057E+00   4.15864E+00

   1    48         Fold Function:   3.17121E-01
   1    48         BP   Function:   1.21951E+01
   1    48         Hopf Function:   1.25816E+00

   1    48         Eigenvalues  :   Stable:   0
   1    48         Eigenvalue  1:   1.25816E+00  -5.92200E-01
   1    48         Eigenvalue  2:   1.25816E+00   5.92200E-01

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    48        0   1.39057E+00   4.15864E+00   1.39057E+00   3.91927E+00

   1    47         Iterations   :   3
   1    47         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    49   0        1.37618E+00   4.19175E+00
   1    49   1        1.37641E+00   4.19198E+00
   1    49   2        1.37641E+00   4.19198E+00
   1    49   3        1.37641E+00   4.19198E+00

   1    49         Fold Function:   3.11958E-01
   1    49         BP   Function:   1.21458E+01
   1    49         Hopf Function:   1.27774E+00

   1    49         Eigenvalues  :   Stable:   0
   1    49         Eigenvalue  1:   1.27774E+00  -5.11741E-01
   1    49         Eigenvalue  2:   1.27774E+00   5.11741E-01

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    49        0   1.37641E+00   4.19198E+00   1.37641E+00   3.95957E+00

   1    48         Iterations   :   3
   1    48         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    50   0        1.36226E+00   4.22549E+00
   1    50   1        1.36249E+00   4.22571E+00
   1    50   2        1.36249E+00   4.22571E+00
   1    50   3        1.36249E+00   4.22571E+00

   1    50         Fold Function:   3.06871E-01
   1    50         BP   Function:   1.20986E+01
   1    50         Hopf Function:   1.29681E+00

   1    50         Eigenvalues  :   Stable:   0
   1    50         Eigenvalue  1:   1.29681E+00  -4.17916E-01
   1    50         Eigenvalue  2:   1.29681E+00   4.17916E-01

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    50        0   1.36249E+00   4.22571E+00   1.36249E+00   4.00003E+00

   1    49         Iterations   :   3
   1    49         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    51   0        1.34857E+00   4.25961E+00
   1    51   1        1.34879E+00   4.25983E+00
   1    51   2        1.34879E+00   4.25982E+00
   1    51   3        1.34879E+00   4.25982E+00

   1    51         Fold Function:   3.01861E-01
   1    51         BP   Function:   1.20534E+01
   1    51         Hopf Function:   1.31538E+00

   1    51         Eigenvalues  :   Stable:   0
   1    51         Eigenvalue  1:   1.31538E+00  -2.98359E-01
   1    51         Eigenvalue  2:   1.31538E+00   2.98359E-01

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    51        0   1.34879E+00   4.25982E+00   1.34879E+00   4.04065E+00

   1    50         Iterations   :   3
   1    50         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    52   0        1.33510E+00   4.29409E+00
   1    52   1        1.33532E+00   4.29431E+00
   1    52   2        1.33532E+00   4.29431E+00
   1    52   3        1.33532E+00   4.29431E+00

   1    52         Fold Function:   2.96927E-01
   1    52         BP   Function:   1.20101E+01
   1    52         Hopf Function:   1.33346E+00

   1    52         Eigenvalues  :   Stable:   0
   1    52         Eigenvalue  1:   1.33346E+00  -7.04516E-02
   1    52         Eigenvalue  2:   1.33346E+00   7.04516E-02

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    52        0   1.33532E+00   4.29431E+00   1.33532E+00   4.08142E+00

   1    51         Iterations   :   3
   1    51         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    53   0        1.32185E+00   4.32894E+00
   1    53   1        1.32207E+00   4.32914E+00
   1    53   2        1.32207E+00   4.32914E+00
   1    53   3        1.32207E+00   4.32914E+00

   1    53         Fold Function:   2.92072E-01
   1    53         BP   Function:   1.19686E+01
   1    53         Hopf Function:   0.00000E+00

   1    53         Eigenvalues  :   Stable:   0
   1    53         Eigenvalue  1:   1.62950E+00   0.00000E+00
   1    53         Eigenvalue  2:   1.07264E+00   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    53        0   1.32207E+00   4.32914E+00   1.32207E+00   4.12233E+00

   1    52         Iterations   :   3
   1    52         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    54   0        1.30882E+00   4.36412E+00
   1    54   1        1.30903E+00   4.36432E+00
   1    54   2        1.30903E+00   4.36432E+00
   1    54   3        1.30903E+00   4.36432E+00

   1    54         Fold Function:   2.87295E-01
   1    54         BP   Function:   1.19289E+01
   1    54         Hopf Function:   0.00000E+00

   1    54         Eigenvalues  :   Stable:   0
   1    54         Eigenvalue  1:   1.76628E+00   0.00000E+00
   1    54         Eigenvalue  2:   9.70156E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    54        0   1.30903E+00   4.36432E+00   1.30903E+00   4.16338E+00

   1    53         Iterations   :   3
   1    53         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    55   0        1.29600E+00   4.39964E+00
   1    55   1        1.29621E+00   4.39983E+00
   1    55   2        1.29621E+00   4.39983E+00
   1    55   3        1.29621E+00   4.39983E+00

   1    55         Fold Function:   2.82596E-01
   1    55         BP   Function:   1.18908E+01
   1    55         Hopf Function:   0.00000E+00

   1    55         Eigenvalues  :   Stable:   0
   1    55         Eigenvalue  1:   1.87261E+00   0.00000E+00
   1    55         Eigenvalue  2:   8.97229E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    55        0   1.29621E+00   4.39983E+00   1.29621E+00   4.20457E+00

   1    54         Iterations   :   3
   1    54         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    56   0        1.28339E+00   4.43548E+00
   1    56   1        1.28360E+00   4.43566E+00
   1    56   2        1.28360E+00   4.43566E+00
   1    56   3        1.28360E+00   4.43566E+00

   1    56         Fold Function:   2.77976E-01
   1    56         BP   Function:   1.18543E+01
   1    56         Hopf Function:   0.00000E+00

   1    56         Eigenvalues  :   Stable:   0
   1    56         Eigenvalue  1:   1.96307E+00   0.00000E+00
   1    56         Eigenvalue  2:   8.39310E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    56        0   1.28360E+00   4.43566E+00   1.28360E+00   4.24588E+00

   1    55         Iterations   :   3
   1    55         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    57   0        1.27098E+00   4.47162E+00
   1    57   1        1.27119E+00   4.47180E+00
   1    57   2        1.27119E+00   4.47180E+00
   1    57   3        1.27119E+00   4.47180E+00

   1    57         Fold Function:   2.73435E-01
   1    57         BP   Function:   1.18194E+01
   1    57         Hopf Function:   0.00000E+00

   1    57         Eigenvalues  :   Stable:   0
   1    57         Eigenvalue  1:   2.04319E+00   0.00000E+00
   1    57         Eigenvalue  2:   7.90884E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    57        0   1.27119E+00   4.47180E+00   1.27119E+00   4.28732E+00

   1    56         Iterations   :   3
   1    56         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    58   0        1.25878E+00   4.50807E+00
   1    58   1        1.25899E+00   4.50824E+00
   1    58   2        1.25899E+00   4.50824E+00
   1    58   3        1.25899E+00   4.50824E+00

   1    58         Fold Function:   2.68972E-01
   1    58         BP   Function:   1.17859E+01
   1    58         Hopf Function:   0.00000E+00

   1    58         Eigenvalues  :   Stable:   0
   1    58         Eigenvalue  1:   2.11580E+00   0.00000E+00
   1    58         Eigenvalue  2:   7.49147E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    58        0   1.25899E+00   4.50824E+00   1.25899E+00   4.32888E+00

   1    57         Iterations   :   3
   1    57         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    59   0        1.24678E+00   4.54480E+00
   1    59   1        1.24698E+00   4.54496E+00
   1    59   2        1.24698E+00   4.54496E+00
   1    59   3        1.24698E+00   4.54496E+00

   1    59         Fold Function:   2.64588E-01
   1    59         BP   Function:   1.17538E+01
   1    59         Hopf Function:   0.00000E+00

   1    59         Eigenvalues  :   Stable:   0
   1    59         Eigenvalue  1:   2.18260E+00   0.00000E+00
   1    59         Eigenvalue  2:   7.12438E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    59        0   1.24698E+00   4.54496E+00   1.24698E+00   4.37055E+00

   1    58         Iterations   :   3
   1    58         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    60   0        1.23498E+00   4.58180E+00
   1    60   1        1.23517E+00   4.58196E+00
   1    60   2        1.23517E+00   4.58196E+00
   1    60   3        1.23517E+00   4.58196E+00

   1    60         Fold Function:   2.60282E-01
   1    60         BP   Function:   1.17230E+01
   1    60         Hopf Function:   0.00000E+00

   1    60         Eigenvalues  :   Stable:   0
   1    60         Eigenvalue  1:   2.24467E+00   0.00000E+00
   1    60         Eigenvalue  2:   6.79678E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    60        0   1.23517E+00   4.58196E+00   1.23517E+00   4.41234E+00

   1    59         Iterations   :   3
   1    59         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    61   0        1.22336E+00   4.61907E+00
   1    61   1        1.22356E+00   4.61923E+00
   1    61   2        1.22356E+00   4.61923E+00
   1    61   3        1.22356E+00   4.61923E+00

   1    61         Fold Function:   2.56053E-01
   1    61         BP   Function:   1.16935E+01
   1    61         Hopf Function:   0.00000E+00

   1    61         Eigenvalues  :   Stable:   0
   1    61         Eigenvalue  1:   2.30279E+00   0.00000E+00
   1    61         Eigenvalue  2:   6.50119E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    61        0   1.22356E+00   4.61923E+00   1.22356E+00   4.45423E+00

   1    60         Iterations   :   3
   1    60         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    62   0        1.21194E+00   4.65660E+00
   1    62   1        1.21213E+00   4.65675E+00
   1    62   2        1.21213E+00   4.65675E+00
   1    62   3        1.21213E+00   4.65675E+00

   1    62         Fold Function:   2.51901E-01
   1    62         BP   Function:   1.16653E+01
   1    62         Hopf Function:   0.00000E+00

   1    62         Eigenvalues  :   Stable:   0
   1    62         Eigenvalue  1:   2.35753E+00   0.00000E+00
   1    62         Eigenvalue  2:   6.23216E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    62        0   1.21213E+00   4.65675E+00   1.21213E+00   4.49623E+00

   1    61         Iterations   :   3
   1    61         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    63   0        1.20070E+00   4.69438E+00
   1    63   1        1.20088E+00   4.69452E+00
   1    63   2        1.20088E+00   4.69452E+00
   1    63   3        1.20088E+00   4.69452E+00

   1    63         Fold Function:   2.47825E-01
   1    63         BP   Function:   1.16381E+01
   1    63         Hopf Function:   0.00000E+00

   1    63         Eigenvalues  :   Stable:   0
   1    63         Eigenvalue  1:   2.40932E+00   0.00000E+00
   1    63         Eigenvalue  2:   5.98559E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    63        0   1.20088E+00   4.69452E+00   1.20088E+00   4.53833E+00

   1    62         Iterations   :   3
   1    62         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    64   0        1.18964E+00   4.73239E+00
   1    64   1        1.18982E+00   4.73253E+00
   1    64   2        1.18982E+00   4.73253E+00
   1    64   3        1.18982E+00   4.73253E+00

   1    64         Fold Function:   2.43826E-01
   1    64         BP   Function:   1.16121E+01
   1    64         Hopf Function:   0.00000E+00

   1    64         Eigenvalues  :   Stable:   0
   1    64         Eigenvalue  1:   2.45849E+00   0.00000E+00
   1    64         Eigenvalue  2:   5.75830E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    64        0   1.18982E+00   4.73253E+00   1.18982E+00   4.58052E+00

   1    63         Iterations   :   3
   1    63         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    65   0        1.17876E+00   4.77063E+00
   1    65   1        1.17894E+00   4.77077E+00
   1    65   2        1.17894E+00   4.77077E+00
   1    65   3        1.17894E+00   4.77077E+00

   1    65         Fold Function:   2.39901E-01
   1    65         BP   Function:   1.15872E+01
   1    65         Hopf Function:   0.00000E+00

   1    65         Eigenvalues  :   Stable:   0
   1    65         Eigenvalue  1:   2.50533E+00   0.00000E+00
   1    65         Eigenvalue  2:   5.54775E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    65        0   1.17894E+00   4.77077E+00   1.17894E+00   4.62280E+00

   1    64         Iterations   :   3
   1    64         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    66   0        1.16805E+00   4.80910E+00
   1    66   1        1.16823E+00   4.80923E+00
   1    66   2        1.16823E+00   4.80923E+00
   1    66   3        1.16823E+00   4.80923E+00

   1    66         Fold Function:   2.36050E-01
   1    66         BP   Function:   1.15633E+01
   1    66         Hopf Function:   0.00000E+00

   1    66         Eigenvalues  :   Stable:   0
   1    66         Eigenvalue  1:   2.55005E+00   0.00000E+00
   1    66         Eigenvalue  2:   5.35189E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    66        0   1.16823E+00   4.80923E+00   1.16823E+00   4.66518E+00

   1    65         Iterations   :   3
   1    65         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    67   0        1.15752E+00   4.84778E+00
   1    67   1        1.15769E+00   4.84790E+00
   1    67   2        1.15769E+00   4.84790E+00
   1    67   3        1.15769E+00   4.84790E+00

   1    67         Fold Function:   2.32272E-01
   1    67         BP   Function:   1.15403E+01
   1    67         Hopf Function:   0.00000E+00

   1    67         Eigenvalues  :   Stable:   0
   1    67         Eigenvalue  1:   2.59284E+00   0.00000E+00
   1    67         Eigenvalue  2:   5.16904E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    67        0   1.15769E+00   4.84790E+00   1.15769E+00   4.70764E+00

   1    66         Iterations   :   3
   1    66         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    68   0        1.14716E+00   4.88666E+00
   1    68   1        1.14732E+00   4.88678E+00
   1    68   2        1.14732E+00   4.88678E+00
   1    68   3        1.14732E+00   4.88678E+00

   1    68         Fold Function:   2.28566E-01
   1    68         BP   Function:   1.15183E+01
   1    68         Hopf Function:   0.00000E+00

   1    68         Eigenvalues  :   Stable:   0
   1    68         Eigenvalue  1:   2.63387E+00   0.00000E+00
   1    68         Eigenvalue  2:   4.99779E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    68        0   1.14732E+00   4.88678E+00   1.14732E+00   4.75018E+00

   1    67         Iterations   :   3
   1    67         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    69   0        1.13696E+00   4.92574E+00
   1    69   1        1.13712E+00   4.92586E+00
   1    69   2        1.13712E+00   4.92586E+00
   1    69   3        1.13712E+00   4.92586E+00

   1    69         Fold Function:   2.24932E-01
   1    69         BP   Function:   1.14972E+01
   1    69         Hopf Function:   0.00000E+00

   1    69         Eigenvalues  :   Stable:   0
   1    69         Eigenvalue  1:   2.67326E+00   0.00000E+00
   1    69         Eigenvalue  2:   4.83695E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    69        0   1.13712E+00   4.92586E+00   1.13712E+00   4.79281E+00

   1    68         Iterations   :   3
   1    68         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    70   0        1.12692E+00   4.96501E+00
   1    70   1        1.12708E+00   4.96512E+00
   1    70   2        1.12708E+00   4.96512E+00
   1    70   3        1.12708E+00   4.96512E+00

   1    70         Fold Function:   2.21367E-01
   1    70         BP   Function:   1.14769E+01
   1    70         Hopf Function:   0.00000E+00

   1    70         Eigenvalues  :   Stable:   0
   1    70         Eigenvalue  1:   2.71114E+00   0.00000E+00
   1    70         Eigenvalue  2:   4.68550E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    70        0   1.12708E+00   4.96512E+00   1.12708E+00   4.83551E+00

   1    69         Iterations   :   3
   1    69         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    71   0        1.11704E+00   5.00447E+00
   1    71   1        1.11720E+00   5.00458E+00
   1    71   2        1.11720E+00   5.00458E+00
   1    71   3        1.11720E+00   5.00458E+00

   1    71         Fold Function:   2.17872E-01
   1    71         BP   Function:   1.14574E+01
   1    71         Hopf Function:   0.00000E+00

   1    71         Eigenvalues  :   Stable:   0
   1    71         Eigenvalue  1:   2.74761E+00   0.00000E+00
   1    71         Eigenvalue  2:   4.54259E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    71        0   1.11720E+00   5.00458E+00   1.11720E+00   4.87828E+00

   1    70         Iterations   :   3
   1    70         Next Step    :  -4.50000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    72   0        1.10731E+00   5.04410E+00
   1    72   1        1.10747E+00   5.04421E+00
   1    72   2        1.10747E+00   5.04421E+00

   1    72         Fold Function:   2.14445E-01
   1    72         BP   Function:   1.14388E+01
   1    72         Hopf Function:   0.00000E+00

   1    72         Eigenvalues  :   Stable:   0
   1    72         Eigenvalue  1:   2.78277E+00   0.00000E+00
   1    72         Eigenvalue  2:   4.40744E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    72        0   1.10747E+00   5.04421E+00   1.10747E+00   4.92113E+00

   1    71         Iterations   :   2
   1    71         Next Step    :  -6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    73   0        1.09450E+00   5.09715E+00
   1    73   1        1.09474E+00   5.09731E+00
   1    73   2        1.09474E+00   5.09731E+00
   1    73   3        1.09474E+00   5.09731E+00

   1    73         Fold Function:   2.09980E-01
   1    73         BP   Function:   1.14149E+01
   1    73         Hopf Function:   0.00000E+00

   1    73         Eigenvalues  :   Stable:   0
   1    73         Eigenvalue  1:   2.82773E+00   0.00000E+00
   1    73         Eigenvalue  2:   4.23820E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    73        0   1.09474E+00   5.09731E+00   1.09474E+00   4.97836E+00

   1    72         Iterations   :   3
   1    72         Next Step    :  -6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    74   0        1.08200E+00   5.15053E+00
   1    74   1        1.08227E+00   5.15070E+00
   1    74   2        1.08227E+00   5.15070E+00
   1    74   3        1.08227E+00   5.15070E+00

   1    74         Fold Function:   2.05630E-01
   1    74         BP   Function:   1.13923E+01
   1    74         Hopf Function:   0.00000E+00

   1    74         Eigenvalues  :   Stable:   0
   1    74         Eigenvalue  1:   2.87067E+00   0.00000E+00
   1    74         Eigenvalue  2:   4.08026E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    74        0   1.08227E+00   5.15070E+00   1.08227E+00   5.03571E+00

   1    73         Iterations   :   3
   1    73         Next Step    :  -6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    75   0        1.06980E+00   5.20421E+00
   1    75   1        1.07006E+00   5.20437E+00
   1    75   2        1.07006E+00   5.20437E+00
   1    75   3        1.07006E+00   5.20437E+00

   1    75         Fold Function:   2.01395E-01
   1    75         BP   Function:   1.13709E+01
   1    75         Hopf Function:   0.00000E+00

   1    75         Eigenvalues  :   Stable:   0
   1    75         Eigenvalue  1:   2.91173E+00   0.00000E+00
   1    75         Eigenvalue  2:   3.93247E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    75        0   1.07006E+00   5.20437E+00   1.07006E+00   5.09318E+00

   1    74         Iterations   :   3
   1    74         Next Step    :  -6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    76   0        1.05785E+00   5.25815E+00
   1    76   1        1.05810E+00   5.25830E+00
   1    76   2        1.05810E+00   5.25830E+00
   1    76   3        1.05810E+00   5.25830E+00

   1    76         Fold Function:   1.97270E-01
   1    76         BP   Function:   1.13506E+01
   1    76         Hopf Function:   0.00000E+00

   1    76         Eigenvalues  :   Stable:   0
   1    76         Eigenvalue  1:   2.95104E+00   0.00000E+00
   1    76         Eigenvalue  2:   3.79383E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    76        0   1.05810E+00   5.25830E+00   1.05810E+00   5.15074E+00

   1    75         Iterations   :   3
   1    75         Next Step    :  -6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    77   0        1.04614E+00   5.31234E+00
   1    77   1        1.04638E+00   5.31248E+00
   1    77   2        1.04638E+00   5.31248E+00
   1    77   3        1.04638E+00   5.31248E+00

   1    77         Fold Function:   1.93254E-01
   1    77         BP   Function:   1.13314E+01
   1    77         Hopf Function:   0.00000E+00

   1    77         Eigenvalues  :   Stable:   0
   1    77         Eigenvalue  1:   2.98873E+00   0.00000E+00
   1    77         Eigenvalue  2:   3.66350E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    77        0   1.04638E+00   5.31248E+00   1.04638E+00   5.20841E+00

   1    76         Iterations   :   3
   1    76         Next Step    :  -6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    78   0        1.03467E+00   5.36676E+00
   1    78   1        1.03491E+00   5.36690E+00
   1    78   2        1.03491E+00   5.36690E+00
   1    78   3        1.03491E+00   5.36690E+00

   1    78         Fold Function:   1.89343E-01
   1    78         BP   Function:   1.13131E+01
   1    78         Hopf Function:   0.00000E+00

   1    78         Eigenvalues  :   Stable:   0
   1    78         Eigenvalue  1:   3.02489E+00   0.00000E+00
   1    78         Eigenvalue  2:   3.54073E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    78        0   1.03491E+00   5.36690E+00   1.03491E+00   5.26617E+00

   1    77         Iterations   :   3
   1    77         Next Step    :  -6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    79   0        1.02343E+00   5.42141E+00
   1    79   1        1.02366E+00   5.42155E+00
   1    79   2        1.02366E+00   5.42154E+00
   1    79   3        1.02366E+00   5.42154E+00

   1    79         Fold Function:   1.85535E-01
   1    79         BP   Function:   1.12957E+01
   1    79         Hopf Function:   0.00000E+00

   1    79         Eigenvalues  :   Stable:   0
   1    79         Eigenvalue  1:   3.05963E+00   0.00000E+00
   1    79         Eigenvalue  2:   3.42486E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    79        0   1.02366E+00   5.42154E+00   1.02366E+00   5.32403E+00

   1    78         Iterations   :   3
   1    78         Next Step    :  -6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    80   0        1.01242E+00   5.47628E+00
   1    80   1        1.01264E+00   5.47641E+00
   1    80   2        1.01264E+00   5.47641E+00
   1    80   3        1.01264E+00   5.47641E+00

   1    80         Fold Function:   1.81827E-01
   1    80         BP   Function:   1.12792E+01
   1    80         Hopf Function:   0.00000E+00

   1    80         Eigenvalues  :   Stable:   0
   1    80         Eigenvalue  1:   3.09302E+00   0.00000E+00
   1    80         Eigenvalue  2:   3.31533E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    80        0   1.01264E+00   5.47641E+00   1.01264E+00   5.38197E+00

   1    79         Iterations   :   3
   1    79         Next Step    :  -6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    81   0        1.00162E+00   5.53135E+00
   1    81   1        1.00184E+00   5.53147E+00
   1    81   2        1.00184E+00   5.53147E+00
   1    81   3        1.00184E+00   5.53147E+00

   1    81         Fold Function:   1.78217E-01
   1    81         BP   Function:   1.12636E+01
   1    81         Hopf Function:   0.00000E+00

   1    81         Eigenvalues  :   Stable:   0
   1    81         Eigenvalue  1:   3.12515E+00   0.00000E+00
   1    81         Eigenvalue  2:   3.21163E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
   1    81        0   1.00184E+00   5.53147E+00   1.00184E+00   5.43999E+00

   1    80         Iterations   :   3
   1    80         Next Step    :  -6.00000E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    82   0        9.91039E-01   5.58662E+00
   1    82   1        9.91253E-01   5.58674E+00
   1    82   2        9.91253E-01   5.58673E+00
   1    82   3        9.91253E-01   5.58673E+00

 ==> Location of special point :  Iteration   0  Step size =   4.95726E-02
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    82   0        1.00000E+00   5.54107E+00
   1    82   1        9.99985E-01   5.54106E+00
   1    82   2        9.99985E-01   5.54106E+00

 ==> Location of special point :  Iteration   1  Step size =   8.55291E-05
===============================================

  BR    PT  IT         PAR           L2-NORM
   1    82   0        1.00000E+00   5.54098E+00
   1    82   1        1.00000E+00   5.54098E+00

 ==> Location of special point :  Convergence.   Step size =   1.08034E-09
   1    82         Fold Function:   1.77604E-01
   1    82         BP   Function:   1.12610E+01
   1    82         Hopf Function:   0.00000E+00

   1    82         Eigenvalues  :   Stable:   0
   1    82         Eigenvalue  1:   3.13057E+00   0.00000E+00
   1    82         Eigenvalue  2:   3.19431E-01   0.00000E+00

  BR    PT  TY  LAB       a          L2-NORM          u             v       
